### ISSUE TITLE
Matcher sample code

### ISSUE THREAD

**Issue by sdenning** [spacy-io/spaCy#105]
Can you provide a code snippet of how to use the NER matcher?

**Comment by honnibal** [comment]
Thanks for asking. This has been on the TODO list.

Hopefully enough to get you started:

https://github.com/honnibal/spaCy/blob/master/examples/matcher_example.py

I want to keep improving this functionality. If you want to explain what you're doing, I can offer more specific advice.

**Comment by sdenning** [comment]
I think I figured it out, see below.

from __future__ import unicode_literals

import spacy.en
from spacy.en import English
from spacy.matcher import *


artists = []
bands = []
albums = []
tracks = []

nlp = English()

doc = nlp('One of the most popular bands of all time is U2; Bono and The Edge are simply amazing. ' +
          'My favorite of all their albums is Songs of Innocence though The Joshua Tree is a close second. ' +
          'Every breaking wave, Song for Someone, and California are some of my favorite songs.')

# create the patterns for the matcher
patterns = {

  'Band':['BAND',{},[[{'orth': 'U2'}]]],

  'Albums':[
    'ALBUM',{},[
      [{'lower': 'songs'},{'lower': 'of'},{'lower': 'innocence'}],
      [{'lower': 'the'},{'lower': 'joshua'},{'lower': 'tree'}]
    ]
  ],

  'Tracks':  [
    'TRACK',{},[
      [{'lower': 'california'}],
      [{'lower': 'cedarwood'},{'lower': 'road'}],
      [{'lower': 'every'},{'lower': 'breaking'},{'lower': 'wave'}],
      [{'lower': 'iris'}],
      [{'lower': 'the'},{'lower': 'miricle'}], 
      [{'lower': 'raised'},{'lower': 'by'},{'lower': 'wolves'}],
      [{'lower': 'sleep'},{'lower': 'like'},{'lower': 'a'},{'lower': 'baby'},{'lower': 'tonight'}],  
      [{'lower': 'song'},{'lower': 'for'},{'lower': 'someone'}],
      [{'lower': 'this'},{'lower': 'is'},{'lower': 'where'},{'lower': 'yo'},{'lower': 'can'},{'lower': 'reach'},{'lower': 'me'},{'lower': 'now'}], 
      [{'lower': 'the'},{'lower': 'troubles'}],
      [{'lower': 'volcano'}]
    ]
  ]
}

#create the matcher
matcher = Matcher(doc.vocab, patterns)

# let's add a new pattern to the matcher
key = 'Artists'
etype = 'ARTIST'
attrs = {}
specs = [[{'orth': 'Bono'}],[{'lower': 'the'},{'orth': 'Edge'}]]

matcher.add(key, etype, attrs, specs) 

# get the matcher to look at the doc and update the ents
matcher.__call__(doc)

for ent in doc.ents:

  if ent.label_ == 'BAND':
    bands.append(ent.orth_)
  elif ent.label_ == 'ARTIST':
    artists.append(ent.orth_)
  elif ent.label_ == 'ALBUM':
    albums.append(ent.orth_)
  elif ent.label_ == 'TRACK': 
    tracks.append(ent.orth_) 

print 'bands: ' + str(bands)
print 'artists: ' + str(artists)
print 'albums: ' + str(albums)
print 'tracks: ' + str(tracks)

**Comment by honnibal** [comment]
Looks good. Btw, instead of:
```python
 matcher.__call__(doc)
```

You can write

```python
matcher(doc)
```

the `__call__` is how you define `operator()` in Python.

**Comment by sdenning** [comment]
Thanks, though I’ve been working in Python for quite a while I’m always amazed at how much I still have to learn.


On Sep 27, 2015, at 10:11 AM, Matthew Honnibal <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks good. Btw, instead of:

 matcher.__call__(doc)

You can write

matcher(doc)

the __call__ is how you define operator() in Python.

**Comment by dandxy89** [comment]
Very helpful, very pleased I can now keep the majority of my NLP tasks within SpaCy. Thanks for this!

**Comment by honnibal** [comment]
Closing this out — the new and improved `Matcher` functionality will be in 1.0. See Issue #506 .

**Comment by m93s** [comment]
@sdenning , I've been trying your code snippet but I keep getting empty lists. I'm using spaCy version 1.7.
However, if I add patterns to the matcher like `matcher= Matcher(nlp.vocab,patterns)`  and then run `matches = matcher(doc)` , my matches list is populated. But these patterns aren't recognized as entities.
@honnibal , the code present at [https://github.com/honnibal/spaCy/blob/master/examples/matcher_example.py](url) doesn't give the output mentioned. Instead, the output is 
```
Before
Google Now PERSON [u'NNP', u'RB']
After
Google Now PERSON [u'NNP', u'RB']
Sydney True
sydney False
Sydney True
sydney True
SYDNEY True
the Brisbane Broncos ORG

```
Is this because I'm using a different version?

**Comment by adack123** [comment]
@m93s 

I'm also getting similar results when running the example from the docs.
