### ISSUE TITLE
Is there any trick to quickly load glove vectors? ~2GB

### ISSUE THREAD

**Issue by arushk1** [spacy-io/spaCy#175]
Currently, importing the glove vectors from the statement, nlp = English() takes an embarrassing amount of time. Is there any way to decrease that? It's on an ubuntu server on Azure. And I intend to run it on a website.

**Comment by honnibal** [comment]
Do you really need all of the entries? The effect of extending the vocabulary shrinks exponentially. Even spaCy's default vocabulary size of 1 million is probably overly generous, and should be cut down to a smaller number.

If you load only 500,000 or so vectors from GloVe, for the most common words (using the lexeme.prob field provided by spaCy, or your own counts from your domain), you'll probably achieve very similar coverage to what you're achieving with all of GloVe.

The main applications I can think of for using all of GloVe are named entity things, and spelling correction.

**Comment by ahirner** [comment]
@honnibal what is the recommended way to prevent loading the GloVe vectors? The docs state that you can choose to load/not load the parser, tagger and ER. Which parts are affected by or effect a missing vector lookup?

**Comment by honnibal** [comment]
There's currently no great way to prevent loading the vectors. We're working on this.

The best way to load the GloVe vectors is now:

```
sputnik --name spacy install en_glove_cc_300_1m_vectors-1.0.0
```

```python

import spacy

nlp = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')
```

**Comment by avishek15** [comment]
```python
import spacy

nlp = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')
```
returns the following error. What am I doing wrong?

```python
Traceback (most recent call last):
  File "spacy_1.py", line 3, in <module>
    nlp = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')
  File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 16, in load
    vectors_package = get_package_by_name(vectors, via=via)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 41, in get_package_by_name
    lang = get_lang_class(name)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 28, in get_lang_class
    raise RuntimeError('Language not supported: %s' % lang)
RuntimeError: Language not supported: en_glove_cc_300_1m_vectors
```

Please Suggest.

**Comment by daylen** [comment]
@avishek15 See https://github.com/spacy-io/spaCy/issues/338 -- there's a bug with how spacy parses the language from the filename.
