### ISSUE TITLE
Inconsistent token.rights?

### ISSUE THREAD

**Issue by viksit** [spacy-io/spaCy#179]
Example,

```
a = nlp(u"I'd like a flight from San Francisco to Los Angeles")
[(tok.text, map(lambda x: x.text, list(tok.rights))) for tok in a]
[(u'I', []),
 (u"'d", []),
 (u'like', [u'flight']),
 (u'a', []),
 (u'flight', [u'from', u'to']),
 (u'from', [u'Francisco']),
 (u'San', []),
 (u'Francisco', []),
 (u'to', [u'Angeles']),
 (u'Los', []),
 (u'Angeles', [])]

```

Shouldn't from -> San Francisco and to -> Los Angeles? Or am I understanding the ```rights()``` incorrectly?

**Comment by honnibal** [comment]
By default names aren't merged into single tokens, so "San Francisco" is understood as two tokens, headed by "Francisco".

It's a little confusing because the displaCy visualizer does merge these, mostly for visual simplicity.

**Comment by viksit** [comment]
@honnibal ah I see. Is getting the root or the head the best way to get the whole word then?

**Comment by honnibal** [comment]
You should do something like:

```python
for ent in doc.ents:
  ent.merge(ent.root.tag_, ent.text, ent.label_)
```
