### ISSUE TITLE
pip install doesn't work on El Capitan

### ISSUE THREAD

**Issue by Shashwat986** [spacy-io/spaCy#196]
I was trying to install spaCy on my Mac OS X El Capitan (10.11.1).

It seems to be throwing the following error:

    reading manifest file 'pip-egg-info/spacy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/spacy.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-pC4HnQ/spacy/setup.py", line 231, in <module>
        main(MOD_NAMES, use_cython)
      File "/private/tmp/pip-build-pC4HnQ/spacy/setup.py", line 207, in main
        run_setup(exts)
      File "/private/tmp/pip-build-pC4HnQ/spacy/setup.py", line 190, in run_setup
        headers_workaround.install_headers('murmurhash')
      File "/private/tmp/pip-build-pC4HnQ/spacy/headers_workaround-0.18-py2.7.egg/headers_workaround/__init__.py", line 33, in install_headers
        shutil.copytree(src_dir, dest_dir)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 177, in copytree
        os.makedirs(dst)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/include/murmurhash'

As far as I can understand, this is because, by default, the System Integrity Protection (rootless) feature in El Capitan disallows file/folder creation in the `/System/Library` folder.

I was wondering if this was a known bug, and whether there existed a workaround. Failing that, I will probably disable rootless and install spaCy, but I'd rather not do that unless I must.

Thanks a lot, and I really love this module! Great work!

**Comment by honnibal** [comment]
I usually install into a virtualenv, but conda and pyenv are also both good options. I wouldn't recommend to install into the system directory anyway --- it usually causes a lot of trouble!

**Comment by Shashwat986** [comment]
conda worked for me, thanks!

**Comment by sdenning** [comment]
No, there really is something wrong with pip on El Capitan. I'm trying to upgrade spacy and my install directory is /Library/Python/2.7/site-packages.
Here's the error trace:

$ sudo pip install --upgrade spacy
Downloading/unpacking spacy from https://pypi.python.org/packages/source/s/spacy/spacy-0.99.tar.gz#md5=a2d1a2617517dfde37b5c5ede0c25c22
  Downloading spacy-0.99.tar.gz (4.1MB): 4.1MB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/spacy/setup.py) egg_info for package spacy
    zip_safe flag not set; analyzing archive contents...
    headers_workaround.__init__: module references __file__

    Installed /private/tmp/pip_build_root/spacy/.eggs/headers_workaround-0.18-py2.7.egg

    package init file 'spacy/tests/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/matcher/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/morphology/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/munge/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/parser/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/serialize/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/spans/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/tagger/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/tokenizer/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/tokens/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/vectors/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/vocab/__init__.py' not found (or not a regular file)
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/tmp/pip_build_root/spacy/setup.py", line 231, in <module>
        main(MOD_NAMES, use_cython)
      File "/private/tmp/pip_build_root/spacy/setup.py", line 207, in main
        run_setup(exts)
      File "/private/tmp/pip_build_root/spacy/setup.py", line 190, in run_setup
        headers_workaround.install_headers('murmurhash')
      File "/private/tmp/pip_build_root/spacy/.eggs/headers_workaround-0.18-py2.7.egg/headers_workaround/__init__.py", line 33, in install_headers
        shutil.copytree(src_dir, dest_dir)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 177, in copytree
        os.makedirs(dst)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/include/murmurhash'
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...

**Comment by sdenning** [comment]
Here's a thread discussing possible solutions:
http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-el-capitan-max-os-x-upgrade

**Comment by honnibal** [comment]
I really recommend not relying on installing into the system paths. conda, virtualenv, or pyenv are all good options.

**Comment by henningpeters** [comment]
In the meantime we replaced the headers_workaround package that was trying to write to a global folder and published new pip and conda packages. Hence, I assume this issue can be considered solved.

**Comment by sdenning** [comment]
Very nice. Thank you.
On Feb 8, 2016, at 8:49 AM, Henning Peters <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #196<https://github.com/spacy-io/spaCy/issues/196>.
