### ISSUE TITLE
Replacing pos tagger

### ISSUE THREAD

**Issue by Aequivinius** [spacy-io/spaCy#211]
Dear honnibal

We're experimenting with the spacy parser and use it for the biomedical domain. However, the pos tagger and as a consequence the parser do not cope well with these specialised texts. Is there a good way to provide a test that is already tagged by other means to the spacy parser; or to train the spacy tagger on our own data? Kind regards,
 - Nico

**Comment by honnibal** [comment]
You can pre-specify tags in a few ways. The `Tagger.tag_from_strings` method accepts a `Doc` object and a list of strings, and assigns the POS tags.

What are you using for POS tags? Do you have gold tags? You could just retrain the tagger. You might want to change some things in the tokenization, too. Also if you have gazetteers, the `spacy.matcher.Matcher` and `spacy.matcher.PhraseMatcher` classes are likely to be of interest.
