### ISSUE TITLE
FAC in named entities

### ISSUE THREAD

**Issue by aborsu** [spacy-io/spaCy#229]
Hello,

(First of all thank you for a magnificent piece of programming)
I'm trying out the NER capabilities of spaCy and I noticed that I have some entities with the FAC tag, which I suppose from looking at them are FACILITY type entities.
In the [specs](https://spacy.io/docs#spec) though they are listed as FACILITY but I found none.
Might want to correct either the specs or the annotator.

**Comment by honnibal** [comment]
Thanks, will do.

**Comment by thisisjeffchen** [comment]
Guys, I just encountered this as well. I put in a work around in my code, but FAC should probably be deleted from where ever it's generated :)

**Comment by ivyleavedtoadflax** [comment]
I've just experienced this too: ![image](https://user-images.githubusercontent.com/4583655/39663273-1c913c0a-5068-11e8-9f6a-813d0cd0082a.png)
