### ISSUE TITLE
Question about adding entities to the NER

### ISSUE THREAD

**Issue by antikantian** [spacy-io/spaCy#247]
First off, spaCy is phenomenal.  At any rate, I just had a quick question about adding entities to the NER via matcher.add.  Is this a one-time operation, or does it need to be done at every import?  Thanks.

**Comment by honnibal** [comment]
Thanks!

`matcher.add` updates the local state, so you'll have to set this each time you load the pipeline.

**Comment by antikantian** [comment]
Ah, that's what I figured.  Thanks!

P.S. The new update is amazing.  Load times have decreased dramatically!
