### ISSUE TITLE
Error running the examples

### ISSUE THREAD

**Issue by davidsbatista** [spacy-io/spaCy#254]
I installed spaCy like this:

`sudo pip install spacy`

and all went smooth:

`Successfully installed spacy`
`Cleaning up...`

But whenever I try to run the example, I get this error message:

`>>> from spacy.en import English`
`>>> nlp = English()`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/lib/python2.7/dist-packages/spacy/language.py", line 223, in __init__`
`    package = util.get_package_by_name()`
`  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 26, in get_package_by_name`
`    name or about.__default_model__, data_path=via)`
`  File "/usr/local/lib/python2.7/dist-packages/sputnik/__init__.py", line 159, in package`
`    pool = Pool(app_name, app_version, expand_path(data_path))`
`  File "/usr/local/lib/python2.7/dist-packages/sputnik/pool.py", line 20, in __init__`
`    super(Pool, self).__init__(app_name, app_version, path, **kwargs)`
`  File "/usr/local/lib/python2.7/dist-packages/sputnik/package_list.py", line 35, in __init__`
`    self.load()`
`  File "/usr/local/lib/python2.7/dist-packages/sputnik/package_list.py", line 53, in load`
`    for package in self.packages():`
`  File "/usr/local/lib/python2.7/dist-packages/sputnik/package_list.py", line 39, in packages`
`    os.makedirs(self.path)`
`  File "/usr/lib/python2.7/os.py", line 157, in makedirs`
`    mkdir(name, mode)`
`OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/spacy/data'`

**Comment by henningpeters** [comment]
Thanks for the report. It looks to me as if its a simple permission problem thats easy to solve.

Did you run ```spacy -m spacy.en.download```? In case it results in the same error please run it with a user that has access to the directory ```/usr/local/lib/python2.7/dist-packages/spacy/data```.

Generally, it is recommended to use virtualenv, pyenv, conda, pip in --user mode or similar to have python/pip not use global installation directories that require admin privileges. This is a general python best practice advice that's not only applicable to spaCy.

Some more background: by default spaCy uses the installation directory (in your case ```/usr/local/lib/python2.7/dist-packages/spacy/data```) to store its models that you can download/install via ```python -m spacy.en.download```. Hence, you need to have proper permissions to write these models to that directory. Once installed, when running ```nlp = English()``` only read-permissions are needed.

**Comment by davidsbatista** [comment]
ok, got it, run python -m spacy.en.download with the same user and got it running. Thank you :)

**Comment by herlimenezes** [comment]
Same error, running python 3.5 on Jupyter Notebook:
PermissionError                           Traceback (most recent call last)
<ipython-input-1-012530ed0ecd> in <module>()
      2 import pandas as pd
      3 import itertools as it
----> 4 nlp = spacy.load('en')

/usr/lib64/python3.5/site-packages/spacy/__init__.py in load(name, vocab, tokenizer, parser, tagger, entity, matcher, serializer, vectors, via)
     13 def load(name, vocab=None, tokenizer=None, parser=None, tagger=None, entity=None,
     14          matcher=None, serializer=None, vectors=None, via=None):
---> 15     package = get_package_by_name(name, via=via)
     16     vectors_package = get_package_by_name(vectors, via=via)
     17     cls = get_lang_class(name)

/usr/lib64/python3.5/site-packages/spacy/util.py in get_package_by_name(name, via)
     42     try:
     43         return sputnik.package(about.__title__, about.__version__,
---> 44             name, data_path=via)
     45     except PackageNotFoundException as e:
     46         raise RuntimeError("Model '%s' not installed. Please run 'python -m "

/usr/lib/python3.5/site-packages/sputnik/__init__.py in package(app_name, app_version, package_string, data_path)
    157         data_path = default_data_path(app_name)
    158 
--> 159     pool = Pool(app_name, app_version, expand_path(data_path))
    160     return pool.get(package_string)
    161 

/usr/lib/python3.5/site-packages/sputnik/pool.py in __init__(self, app_name, app_version, path, **kwargs)
     17 
     18     def __init__(self, app_name, app_version, path, **kwargs):
---> 19         super(Pool, self).__init__(app_name, app_version, path, **kwargs)
     20         self.logger = logging.getLogger(__name__)
     21         self.cleanup()

/usr/lib/python3.5/site-packages/sputnik/package_list.py in __init__(self, app_name, app_version, path, **kwargs)
     31             raise InvalidDataPathException(self.data_path)
     32 
---> 33         self.load()
     34 
     35     def packages(self):

/usr/lib/python3.5/site-packages/sputnik/package_list.py in load(self)
     49     def load(self):
     50         self._packages = {}
---> 51         for package in self.packages():
     52             self._packages[package.ident] = package
     53 

/usr/lib/python3.5/site-packages/sputnik/package_list.py in packages(self)
     35     def packages(self):
     36         if not os.path.exists(self.path):
---> 37             os.makedirs(self.path)
     38 
     39         for path in os.listdir(self.path):

/usr/lib64/python3.5/os.py in makedirs(name, mode, exist_ok)
    239             return
    240     try:
--> 241         mkdir(name, mode)
    242     except OSError:
    243         # Cannot rely on checking for EEXIST, since the operating system

PermissionError: [Errno 13] Permission denied: '/usr/lib64/python3.5/site-packages/spacy/data'

**Comment by honnibal** [comment]
There shouldn't be anything with `sputnik` in recent versions --- what version are you running?
