### ISSUE TITLE
Errror installing SpaCy

### ISSUE THREAD

**Issue by simonedu** [spacy-io/spaCy#256]
I am trying to install Spacy under Fedora 23. This the error I get:

Command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_z_s9nyj/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fzbps0iq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_z_s9nyj/numpy

**Comment by henningpeters** [comment]
Thanks for the report, it looks to me like a installation/compile problem of numpy that we should be able to resolve. Numpy itself is a spaCy dependency and hence gets installed once you install spaCy via pip or conda.

Could you please give some more information on:
- can you confirm that you used pip to install spaCy?
- what version of pip are you using ```pip --version```? If you are not running a recent pip (>= 7) please upgrade pip with ```pip install -U pip```.
- do you have a build system installed (installation of Python C-extensions via pip require to have a working compiler setup), i.e., ```yum groupinstall "Development Tools" "Development Libraries"```.

Also, could you please reformat your error using triple-backticks (```)? That would make your post more readable. For more details on GitHub's formatting rules see: https://guides.github.com/features/mastering-markdown/

**Comment by honnibal** [comment]
Could you give the rest of the error? It could be as simple as a permission error, if you tried to do a system install and didn't use `sudo`.

**Comment by simonedu** [comment]
Solved. Indeed, the problem was not using sudo. Thank you very much for your assistance.
