### ISSUE TITLE
Consider using rule-based part-of-speech tagging

### ISSUE THREAD

**Issue by mikepb** [spacy-io/spaCy#257]
Thank you for writing such a great library!

The purpose of this issue is to explore and perhaps implement the use of rule-based POS tagging.

I found [RDRPOSTagger][rdrpos] while searching for a faster tagger than NLTK provides. I was consider implementing it, but found spaCy was sufficient for my needs. I wanted to make note of this tagger for spaCy.

According to the [RDRPOSTagger project website][rdrpos], the algorithm achieves:

- 90K words/second
- 96.49% accuracy as compared to the "state of the art" TnT tagger accuracy of 96.46%
- 93.42% accuracy for Vietnamese using 28k corpus

To-do:

- [ ] Compare accuracy of RDRPOSTagger and spaCy perceptron tagger against gold standard. Note: define what is gold standard.
- [ ] Study RDRPOSTagger code for scope of work to Cython. Note: RDRPOSTagger implemented in Python.

[rdrpos]: http://rdrpostagger.sourceforge.net

**Comment by syllog1sm** [comment]
I think you'll find that spaCy's tagger achieves more than 90k words per second. TnT tagger is also far from state of the art.

spaCy's tagger achieves between 97 and 97.3% accuracy on the standard evaluation. There are more accurate taggers in the literature, but not by much. Accuracy generally tops out at about 97.45.

Feel free to implement a rule-based tagger if you want one, but I doubt we'll accept the pull request. Having more than one tagging model will cause a lot of problems.

**Comment by mikepb** [comment]
Thank you for the feedback and clarification! I'm definitely not very familiar with taggers nor the literature. 90k per minute is definitely the kind of performance I'm looking for. Cheers!
