### ISSUE TITLE
Can't pip install

### ISSUE THREAD

**Issue by danielravina** [spacy-io/spaCy#269]
Hello,
I'm getting all of those [errors](https://gist.github.com/danielravina/c0bdf2eeff5b6f20fa82) when doing `pip install spacy` with `virtualenv`. Anyone know what might went wrong?

Thank you!

**Comment by henningpeters** [comment]
It looks to me as if your build system is not complete, specifically some system headers are missing, e.g., limits.h. Do you have the XCode command line tools installed? Please try (re-)install them via ```xcode-select --install```. The spaCy pip package contains C++ code that requires compilation. This in turn demands that the system on which it is installed has a compiler, system headers and python development headers available.

**Comment by danielravina** [comment]
Working! Thank you!!
