### ISSUE TITLE
Can I look up synonyms with spaCy?

### ISSUE THREAD

**Issue by shueffner** [spacy-io/spaCy#276]
Title says it all, I guess :-)
I'm trying to replace NLTK with spaCy and ran into this little corner. In NLTK I use synsets, which are not the same as synonym of course, but do the trick for now. I know that wordnet is somehow bundled into the spacy corpora, any way to use that?

**Comment by honnibal** [comment]
If you have a look at the semantic relatedness produced by this model: sense2vec.spacy.io , would these results be sufficient for you?

We don't have this integrated into spaCy yet. But that's the plan. For now you could use the built-in word vectors. The following function is relatively slow. You should probably iterate over the vocab and cache all the results.

```python
>>> def most_similar(word):
...     by_similarity = sorted(word.vocab, key=lambda w: word.similarity(w), reverse=True)
...     return [w.orth_ for w in by_similarity[:10]]
... 
>>> most_similar(nlp.vocab[u'dog'])
[u'dog', u'Dog', u'DOG', u'DoG', u'doG', u'cat', u'Cat', u'CAT', u'dogs', u'Dogs']
>>> most_similar(nlp.vocab[u'scrape'])
[u'scrape', u'Scrape', u'SCRAPE', u'rustle', u'Rustle', u'RUSTLE', u'gouge', u'Gouge', u'GOUGE', u'gnaw']
```

Looking at these results, it'd be nice to make it a bit case sensitive. We should also exclude rare terms:

```python
>>> def most_similar(word):
...   queries = [w for w in word.vocab if w.is_lower == word.is_lower and w.prob >= -15]
...   by_similarity = sorted(queries, key=lambda w: word.similarity(w), reverse=True)
...   return by_similarity[:10]
... 
>>> [w.lower_ for w in most_similar(nlp.vocab[u'dog'])]
[u'dog', u'cat', u'dogs', u'dachshund', u'pig', u'hamster', u'goat', u'rabbit', u'chimp', u'llama']
```

Finally, you can also consider the Brown cluster, as a way to speed up the search:

```python
>>> nlp.vocab[u'dog'].cluster
37
>>> nlp.vocab[u'cat'].cluster
37
>>> nlp.vocab[u'imagination'].cluster
1893
>>> nlp.vocab[u'always'].cluster
15994
>>> nlp.vocab[u'goat'].cluster
57
>>> nlp.vocab[u'pig'].cluster
121
```

Try restricting the candidates to words whose Brown cluster is within some distance of the word you're looking for. I haven't tried this, but it should work pretty well.

**Comment by shueffner** [comment]
Thanks for the detailed reply! I think I'll start with the sense2vec stuff.

**Comment by shueffner** [comment]
Hmm, I'm getting so-so results so far. Not sure I can trust this.
[w.lower_ for w in most_similar(nlp.vocab[u'bank'])]
['bank', 'banks', 'banking', 'lender', 'securities', 'corporation', 'uniqlo', 'brb', 'telco', 'btc']

Also, the word "telco" appears as similar to almost every word I try. I'l lkeep working :-)

**Comment by honnibal** [comment]
You might be better off loading different vectors. The default ones are trained on Wikipedia.

What are you trying to do, more broadly?

**Comment by shueffner** [comment]
Maybe I should just construct my own vectors when I think about it, I have
plenty of data. The process is to train using gensim or something and then
load the vectors through spacy?

Very broadly, I'm trying to compute similarity between short strings.
Strings are similar if they share substrings, but also if they contain
words with similar meanings.
So, "I'm flying with British Airways" and "I'm soaring with British
Airlines" should be similar. So I need to answer the question: Does s1
contain a synonym to any of the words in s2?

**Comment by honnibal** [comment]
This is a task we'd like to get better at. If you have plenty of data and can share it with us, we might be able to compute a model for you.

I'd try training vectors, yes. Try making the tokens different slices of the spaCy analysis. For instance, you can learn a vector for `British_Airways` pretty easily. You can also learn a vector for something like `nsubj_fly|ROOT_dobj`, by preprocessing the data like this:

```python
for ent in doc.ents:
    ent.merge(ent.root.tag_, ent.text, ent.root.ent_type_)
for word in doc:
    left_labels = [w.dep_ for w in word.lefts]
    right.labels = [w.dep_ for w in word.rights]
    label = word.dep_
    text = '{left}_{word}|{label}_{right}'.format(left=left_labels[0] if left_labels else '', word=word.text, right=right_labels[0] if right_labels else '', label=label)
```

**Comment by shueffner** [comment]
Interesting, thank you!
I'm afraid I can't share our data, or open-source it :-(.

As for the broad problem I'm trying to solve, I've been recommended a c
library called simstring. But that would require of course the thesaurus as
one of the inputs...
Smart learning of vectors for our data is something that I've been wanting
to do for a long time now, maybe this will give me the extra push!

**Comment by honnibal** [comment]
Send me an email? matt@spacy.io
We can probably provide a bit more detailed help. We always want to know more about what's working well in production contexts for people.

**Comment by mrittha** [comment]
I would also be interested in this,  and I can give you a very simple use case.
I am working on generating content for a moodle site (https://moodle.org/), which will include a quiz.   Moodle lets you create "cloze" questions in the quiz:
https://docs.moodle.org/22/en/Embedded_Answers_(Cloze)_question_type#Detailed_syntax_explanations
example 1:
{1:SHORTANSWER:=Berlin} is the capital of Germany.

example 2:
Match the following cities with the correct state:
* San Francisco: {1:MULTICHOICE:=California#OK~Arizona#Wrong}
* Tucson: {1:MULTICHOICE:California#Wrong~%100%Arizona#OK}
* Los Angeles: {1:MULTICHOICE:=California#OK~Arizona#Wrong}
* Phoenix: {1:MULTICHOICE:%0%California#Wrong~=Arizona#OK}

Given this ability I'm using spacy to parse some text, then automatically create a the cloze questions by identifying NOUNs,  then replacing them with the cloze code.   In the above example, a good synonym finder would allow good multichoice questions to be made.

**Comment by sldi42** [comment]
I'm running `nlp.vocab[u'dog'].cluster` but every word I try returns a cluster of zero. Am I not loading the vocab when I install?

**Comment by ifadardin** [comment]
i tried:
`>>> def most_similar(word):
...   queries = [w for w in word.vocab if w.is_lower == word.is_lower and w.prob >= -15]
...   by_similarity = sorted(queries, key=lambda w: word.similarity(w), reverse=True)
...   return by_similarity[:10]
... 
>>> [w.lower_ for w in most_similar(nlp.vocab[u'dog'])]
[u'dog', u'cat', u'dogs', u'dachshund', u'pig', u'hamster', u'goat', u'rabbit', u'chimp', u'llama']`

it doesn't work.

is it updated?

**Comment by exepaul** [comment]
I am looking for same result as you shown here : 

I want if i give a word as input like 'Phone' then it should return something like : 

'phone' ==> 'Phones','phones','Phone','Phone's','phone's' 

I think this code will do my job as you shown there : 



```
>>> def most_similar(word):
...     by_similarity = sorted(word.vocab, key=lambda w: word.similarity(w), reverse=True)
...     return [w.orth_ for w in by_similarity[:10]]
... 
>>> most_similar(nlp.vocab[u'dog'])
[u'dog', u'Dog', u'DOG', u'DoG', u'doG', u'cat', u'Cat', u'CAT', u'dogs', u'Dogs']
>>> most_similar(nlp.vocab[u'scrape'])
[u'scrape', u'Scrape', u'SCRAPE', u'rustle', u'Rustle', u'RUSTLE', u'gouge', u'Gouge', u'GOUGE', u'gnaw']
```

But my result is different from your result when i do : 

```
import spacy
nlp=spacy.load('en_core_web_md')
print('model_loaded')
def most_similar(word):
    by_similarity = sorted(word.vocab, key=lambda w: word.similarity(w), reverse=True)
    print('checked---')
    return [w.orth_ for w in by_similarity[:10]]

print(most_similar(nlp.vocab[u'dog']))

I am getting a result like this : 

`['HOUND', 'Kennel', 'DOG', 'kennel', 'dog', 'canine', 'DoG', 'Dog', 'doG', 'KENNEL']
`
```
Can you let me know which model you are using and how to achieve those result as shown in your code example, if possible can i get that model?

**Comment by pradipcyb** [comment]
I'm also getting all zeros

**Comment by imaurer** [comment]
@pradipcyb and @sldi42 you need to download the large models to get the vectors per the first important note on this page:
https://spacy.io/usage/vectors-similarity

```
>>> spacy.load('en_core_web_lg').vocab['dog'].cluster
37
>>> spacy.load('en').vocab['dog'].cluster
0
```

**Comment by rjsbhatia** [comment]
Hello, 

This works really well; Is there a way to speed up the process? 


thanks

rjs

**Comment by mgulcin** [comment]
@CrossNox 
I had the similar error `AxisError: axis 1 is out of bounds for array of dimension 1` and solved by reshaping the ndarray:

```
tvec = token.vector
most_similar = doc.vocab.vectors.most_similar(tvec.reshape(1,tvec.shape[0]))
```
