### ISSUE TITLE
Is there a way to access NER ID's or arbitrary attributes?

### ISSUE THREAD

**Issue by antikantian** [spacy-io/spaCy#277]
I'm curious as to if there is a way to access these unused fields of the NER.  I know in the example code you state that they are unused at the moment, but is there anything in the code that might be subclass-able or anything else that would be implementable without too much alteration to the spaCy code itself?  Thanks.

P.S. How is the neural network model coming along?  Excited to see that implemented.

**Comment by JoelDapello** [comment]
Bump: I'm also interested in ways to expose NER's attributes; this would add a lot of extensibility I think.

Awesome work with spaCy!

**Comment by honnibal** [comment]
Now in progress! See here: https://github.com/spacy-io/spaCy/issues/499

Closing this as a duplicate.
