### ISSUE TITLE
Install on windows

### ISSUE THREAD

**Issue by CnsAd** [spacy-io/spaCy#279]
Hi
I've installed VS2010 but after running pip to install spacy (`pip install spacy`), it says that Unable to find vcvarsall.bat. what's the problem?

**Comment by CnsAd** [comment]
I have Python **3.5** installed.

**Comment by henningpeters** [comment]
Thats a common distutils/setuptools error that indicates that your build environment couldn't be found. For Python 3.5 you typically need VS 2015 (see https://docs.python.org/devguide/setup.html#windows), I guess that's the problem here.

Btw: we are testing shipping binary wheels, would you help us and try this wheel on your system ?

https://ci.spacy.io/dist/spacy/ee4c4f6a771bacda734824a7000101b6fe083b34/spacy-0.100.5-cp35-none-win_amd64.whl

Please keep in mind that its not an official spaCy release (it is named 0.100.5, but its more of a 0.100.6+dev).

**Comment by CnsAd** [comment]
Thank You very much. I'll test it and inform you.

**Comment by CnsAd** [comment]
I installed the VS2015 and spaCy installed successfully (through PyCharm). TY. but I cant install the wheel you provided above.

**Comment by henningpeters** [comment]
What is the problem/error message when you try installing the wheel? Possibly you have to download it manually first and then run ```pip install -v spacy-0.100.5-cp35-none-win_amd64.whl```. Can you please try that?

**Comment by CnsAd** [comment]
Here is the output message (Is it because of 32 bit /64 bit architecture?):
C:\Users\Ali-PC>pip install -v D:\PRG\PY\spacy-0.100.5-cp35-none-win_amd64.whl
spacy-0.100.5-cp35-none-win_amd64.whl is not a supported wheel on this platform.

Exception information:
Traceback (most recent call last):
  File "c:\users\ali-pc\appdata\local\programs\python\python35-32\lib\site-packa
ges\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "c:\users\ali-pc\appdata\local\programs\python\python35-32\lib\site-packa
ges\pip\commands\install.py", line 287, in run
    wheel_cache
  File "c:\users\ali-pc\appdata\local\programs\python\python35-32\lib\site-packa
ges\pip\basecommand.py", line 270, in populate_requirement_set
    wheel_cache=wheel_cache
  File "c:\users\ali-pc\appdata\local\programs\python\python35-32\lib\site-packa
ges\pip\req\req_install.py", line 219, in from_line
    wheel.filename
pip.exceptions.UnsupportedWheel: spacy-0.100.5-cp35-none-win_amd64.whl is not a
supported wheel on this platform.

**Comment by henningpeters** [comment]
True, its likely that 32-bit Python is the problem. The wheel is built for 64-bit Python. You can check the output of

```
import pip
print(pip.pep425tags.get_supported())
```

whether it contains a wheel filename signature which should match.

Also please note that spaCy is not officially supported on 32-bit Python (see https://github.com/spacy-io/spaCy#supports).

**Comment by hft7h11** [comment]
@henningpeters 
Hi, are any of the wheels for windows still available, that link doesn't seem to be working for me (Currently on windows 10, python 2.7, Anaconda 2)? I'm currently unable to install spacy due to issue 741, so any help would be appreciated, thanks!

**Comment by suren-bhagat** [comment]
https://www.youtube.com/watch?v=cI0zYDJJH78 watch the video for full installation of spacy

**Comment by karst10607** [comment]
The above video is for 64bit, for people who only own 32bit machine or targeting on 32bit mobile devices...does not seem to be much help. 
Does Spacy now support 32bit?
Is there any possible way to compile 32 bit version of Spacy?
Thanks!
