### ISSUE TITLE
improve loading speed

### ISSUE THREAD

**Issue by ssolari** [spacy-io/spaCy#281]
I've just started playing with spacy and it is a very nice package.   Just wanted to throw out a possible suggestion/enhancement on speeding up load speed by using PyTables.  Its quite easy to structure the data or using serialization (like ujson/msgpack) could also enable the fast direct loading of arbitrary python objects without much care for the underlying hdf5 structure.   I suspect there could be at minimum a 3x speedup if not more and could open the door to much more granularity of what to load when for different use cases.   While in production use load time may not matter as much (although speed is always good), in development, the difference between 15s (let alone more) and 3-5s actually makes a pretty big difference in experimenting and debugging.  

I don't know how much interest there is to tackle this.  I'm not at all familiar with how Spacy is storing the data other than it looks like the load is doing some file.read() and split operations to load data.  I can happily provide some example code, but wanted to test the waters first.

**Comment by honnibal** [comment]
Hey,

Actually we've been making good improvements on the loading time. @scoder, the lead maintainer of Cython, has completed a short consulting project for us over the weekend that makes spaCy load more than twice as quickly. If you haven't installed for a while, do

`pip install --upgrade thinc`

This should give you the new model loading code.

The improvements came from saving calls to `fread`, by tweaking the definition of the `thinc.structs.SparseArrayC` struct, defining it as a *padded* struct. This lets us be sure that the size of the struct will be the same across platforms, so we can read in a row with a single system call. This was the major improvement, which halved load time.

Stefan also found a clever way to save another call to `fread`, by grouping two 32 bit integers we were reading independently into another padded struct. This allows us to read them in at the same time. This reduced loading time by another 15% or so.

**Comment by ssolari** [comment]
@honnibal  Awesome work.  Thanks.  I just re-installed and loading the tagger only (or tagger + parser) seemed to improve about ~30-40% for me.   I'm using a solid state disk with macOSx, so maybe that has an impact on the benchmarks.

I still think you could get very large gains above your improvements without even having to write a line of code at the C level.  At the end of the day PyTables is highly optimized has made it so that data can come of disk faster than a memcpy could be done in many cases and this is when the data is compressed (which actually helps).  It might be worth just benchmarking, as the code would not be that complex.   I'm happy to help here if you give me an idea of what is a good test case.

You guys are doing awesome work, so I'm just throwing it out there.  We have been increasingly blown away using HDF5 and compressed data.   Also, if using msgpack to first serialize the data then many of the tricks you are implementing (i.e. storing 32bit or 64bit ints as a single byte) are already done.   So in some sense msgpack + pytables gives significant compression and if you use the blosc compression lib, then data comes off disk amazingly fast.  Note/fyi: careful about trailing null bytes in msgpack with writing to hdf5 with pytables as C trims those, a work-around is to append a non-null byte after serialization before writing to disk and then strip that before deserializing.

Thanks again for the awesome work!

**Comment by ssolari** [comment]
fyi, some benchmarks from my system.

```python
Python 3.5.1 |Anaconda 2.5.0 (x86_64)| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> import time
>>> t1=time.time(); nlp = spacy.en.English(tagger=True, parser=True, entity=True); print(time.time()-t1)
8.46575403213501
>>> t1=time.time(); nlp = spacy.en.English(tagger=True, parser=True, entity=True); print(time.time()-t1)
10.962815999984741
>>> t1=time.time(); nlp = spacy.en.English(tagger=True, parser=True, entity=True); print(time.time()-t1)
10.85429310798645
>>> t1=time.time(); nlp = spacy.en.English(tagger=True, parser=True, entity=True); print(time.time()-t1)
10.780118942260742
>>> t1=time.time(); nlp = spacy.en.English(tagger=True, parser=True, entity=True); print(time.time()-t1)
10.805557012557983
>>>
>>> t1=time.time(); nlp = spacy.en.English(tagger=True, parser=False, entity=False); print(time.time()-t1)
8.81355595588684
>>> t1=time.time(); nlp = spacy.en.English(tagger=True, parser=False, entity=False); print(time.time()-t1)
6.59435510635376
>>> t1=time.time(); nlp = spacy.en.English(tagger=True, parser=False, entity=False); print(time.time()-t1)
6.8132100105285645
>>> t1=time.time(); nlp = spacy.en.English(tagger=True, parser=False, entity=False); print(time.time()-t1)
7.05273699760437
>>> 
```

**Comment by honnibal** [comment]
Honestly I'd be surprised if you could come within 1/10th of our loading speeds if you didn't write any C/Cython code. Have a go :)

Certainly what you're saying about 'faster than memcpy' doesn't make any sense to me. Reading from disk is slow. You could use memmap, but we can't have the memory usage spiking either. So, options are very limited.

**Comment by ssolari** [comment]
I'm not trying to knock what you guys are doing or trying to be offensive.   Frankly I'm really impressed with what you've done with the whole spaCy package and I'm only trying to help contribute to attempt to make your package better.  All the core components of PyTables are C/Cython.  I just mean the wrapper code is at the python level, hence the code for this problem may not need to be "re-"written in C/Cython.   As far as the memcpy comment it has to do with the optimization of data transfer to cache.  Worth checking out: http://www.blosc.org/.

If you want to cast a simple test problem meaningful to the way you organize the data, I can try to create a benchmark.  For all I know my solution will be 1/10th as fast like you said, running an actual test is the only way to tell.   I don't know what a good test problem would be for you.  Write/read a dictionary with 100M unique strings as keys and random 64bit integers as values?  Something else?   Also, if you are  good with current performance, no worries at all, I'm also happy to not do it.  I will still love spaCy! and will close the enhancement issue.

**Comment by honnibal** [comment]
Don't worry there's no offence --- these are simple technical questions.

What I'm saying is that I think we're already at the lowest level here. There's not really much else to say other than that you should try out what speeds you get.

The data format would be:

* Number of rows
* Each row has a 64bit integer key
* Each value has a) an array of integers; an array of doubles
* The two values are of equal length

**Comment by ssolari** [comment]
Ok.  Here are my results.  2.4G worth of data off disk in <2 seconds.  Assuming this is what SpaCy needs then the solution below (compared to my tests above) is about 3-5x faster than what spacy is currently doing on my computer.   Let me know if this is valid for what you were thinking.   Note the randomness below means that the compression is meaningless.

```python
import tables as tb
import numpy as np
import time

n = 1e8
a = np.arange(n).astype(np.int64) # integer key
b = np.random.random_integers(0, 10000, n).astype(np.int64) # integer 
c = np.random.randn(n).astype(np.float64) # double

f = tb.open_file('test.h5', mode='w', complib='blosc', complevel=9)
f.create_carray('/', 'a', obj=a)
f.create_carray('/', 'b', obj=b)
f.create_carray('/', 'c', obj=c)
f.close()

t1 = time.time()
f = tb.open_file('test.h5')
a2 = f.root.a.read()
b2 = f.root.b.read()
c2 = f.root.c.read()
f.close()
tot_t = time.time()-t1
print("Total Time = %.2e, time per row = %.2e" % (tot_t, tot_t/n))
assert np.sum(a2-a)==0
assert np.sum(b2-b)==0
assert np.sum(c2-c)==0
```

**Comment by ssolari** [comment]
Note the results will be faster if b above is a 32bit integer.  The results above are fairly proportional to how much data is being loaded.

**Comment by honnibal** [comment]
Now try it with one read per row...

We can definitely make things faster if we read all the data at once into a
working buffer, and then parse it from memory. But then loading the data
will require 2x the final memory. This is bad because it'll halve the
number of spaCy processes you can run at once on a server.

Now that I get the idea of padded structs I think we might be able to use
memmap. I get the idea behind that now. If we can do that, data loading
will be much quicker.

**Comment by ssolari** [comment]
I agree and get it.  You want to build a sparse array without doubling scratch. The easy and fast solution will temporarily double scratch space if the data has to be reconfigured.  Agreed that PyTables isn't going to be of any benefit if you need to stuff the data into your own C structures especially if you have to iterate.   One last idea is to figure out a hybrid, maybe rather than iterating over every row, you could read in the data in large blocks (like 10-20).   Then just double the data of each block read in scratch temporarily.   

I don't know if this issue helped with any ideas.   There seems to be the possibility to get the data off disk in under 2 sec if the data could be thrown into its final pre-configured structure.  I am definitely not smart enough to do this custom in C, but you guys might be!   Given the discussion and what you are doing  I think this particular issue is closed.   Thanks for engaging.

**Comment by honnibal** [comment]
It did provide useful perspective, thanks. It's good to have a lower bound on the loading time. It's actually a bit lower than I thought it'd be!

I think we should explore whether we can mmap the file, or large chunks of it

**Comment by viksit** [comment]
@honnibal @ssolari interesting discussion here. I've been looking at mmap-ping the word vector files as well recently, and wondered if you've had thoughts there - specifically, that given most learning models need numpy arrays, and mmaping something in numpy formats seems a bit tricky.

**Comment by ssolari** [comment]
My experience is that numpy is commonly the base structure of many learning models.  If the final internal analytic format is a numpy array,  pytables makes getting those arrays to and from disk very easy and very fast.  I have seen anything that comes close.   If the underlying data structure is something other than numpy then that is where I can see mmap or other custom C code being the way to go.
