### ISSUE TITLE
"MemoryError: Error assigning X bytes" on Amazon Linux instance

### ISSUE THREAD

**Issue by bittlingmayer** [spacy-io/spaCy#289]
What does the error [raised on line 42 of cymem.pyx](https://github.com/spacy-io/cymem/search?utf8=%E2%9C%93&q=MemoryError%28%22Error+assigning&type=Code) mean and what could be causing it?

```
    nlp = English()
  File "/home/ec2-user/eb-virt/local/lib64/python2.7/site-packages/spacy/language.py", line 245, in __init__
    parser = self.default_parser(package, self.vocab)
  File "/home/ec2-user/eb-virt/local/lib64/python2.7/site-packages/spacy/language.py", line 177, in default_parser
    return Parser.from_dir(data_dir, vocab.strings, ArcEager)
  File "spacy/syntax/parser.pyx", line 99, in spacy.syntax.parser.Parser.from_dir (spacy/syntax/parser.cpp:5718)
  File "thinc/linear/avgtron.pyx", line 89, in thinc.linear.avgtron.AveragedPerceptron.load (thinc/linear/avgtron.cpp:3092)
  File "preshed/maps.pyx", line 23, in preshed.maps.PreshMap.__init__ (preshed/maps.cpp:1200)
  File "preshed/maps.pyx", line 90, in preshed.maps.map_init (preshed/maps.cpp:2876)
  File "cymem/cymem.pyx", line 42, in cymem.cymem.Pool.alloc (cymem/cymem.c:1014)
MemoryError: Error assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytes
```

This only happens on Amazon Linux EC2 ECB instances, not on OSX.  They are new and relatively clean, with gcc ([installed](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/compile-software.html) via `sudo yum groupinstall "Development Tools"`).
```
Python 2.7.10 (default, Dec  8 2015, 18:25:23) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
```

**Comment by henningpeters** [comment]
I have seen this error before on 32bit systems (arch/Python build). Can you confirm that you are running on 64bit? At the moment we don't support 32bit.

**Comment by bittlingmayer** [comment]
Yes, 64-bit.

<img width="1334" alt="bildschirmfoto 2016-03-14 um 10 24 15" src="https://cloud.githubusercontent.com/assets/11457984/13753123/fb6ca7a0-e9ce-11e5-888e-9cd6a07757f2.png">

It should be straightforward to reproduce: 
1. https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#LaunchInstanceWizard:
2. select the first option (Amazon Linux) and proceed with standard configs (8GB, SSH access only etc)
2.5 create and download credentials (.pem)
3. once the instance is up, SSH to the machine (click "Connect" to see instructions)
4. run python (it's pre-installed)
5. import spaCy etc

Let me know if I can help more or you want me to setup an instance to which you can connect.

**Comment by bittlingmayer** [comment]
```
>>> import sys
>>> sys.maxsize
9223372036854775807
>>> sys.maxsize >> 2**32
0
>>> sys.maxsize > 2**32
True
```

**Comment by henningpeters** [comment]
Hmm, I cannot reproduce the issue from your steps. I've sent you a mail with server credentials.

**Comment by henningpeters** [comment]
It looks like your instace only has 1GB of memory, not 8GB:
```
[ec2-user@ip-172-31-17-101 ~]$ free -m
             total       used       free     shared    buffers     cached
Mem:           995        112        883          0          6         55
-/+ buffers/cache:         50        944
Swap:            0          0          0
```
Looks like this is another instance of #239, no?

**Comment by bittlingmayer** [comment]
Pardon the delay.  It seems so.  As mentioned offline, that was the first instance I spun up, going forward it will be with a repeatable process (ie scripted).  I'm fine if we close this and I will definitely let you know if it comes up again.

**Comment by deathcod** [comment]
Hi,

I am getting the same error. Its showing it when I write `spacy.load('en')`

/usr/local/lib/python3.4/dist-packages/cymem/cymem.pyx in cymem.cymem.Pool.alloc (cymem/cymem.cpp:1091)()
     40         cdef void* p = PyMem_Malloc(number * elem_size)
     41         if p == NULL:
---> 42             raise MemoryError("Error assigning %d bytes" % number * elem_size)
     43         memset(p, 0, number * elem_size)
     44         self.addresses[<size_t>p] = number * elem_size

MemoryError: Error assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytes

**Comment by honnibal** [comment]
Could you paste me the result of `pip list`?

Also if you could tell me whether you're installing on pip or conda?

**Comment by deathcod** [comment]
I have used `pip` 

below is the list 
---------------------

apturl (0.5.2ubuntu4)
backports-abc (0.4)
beautifulsoup4 (4.2.1)
Brlapi (0.6.1)
chardet (2.2.1)
checkbox-ng (0.3)
checkbox-support (0.2)
cloudpickle (0.2.1)
colorama (0.2.5)
command-not-found (0.3)
cymem (1.31.2)
decorator (4.0.10)
defer (1.0.6)
entrypoints (0.2.2)
feedparser (5.1.3)
friends (0.1)
html5lib (0.999)
httplib2 (0.8)
ipykernel (4.5.0)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-contrib-core (0.3.0)
jupyter-contrib-nbextensions (0.2.1)
jupyter-core (4.2.0)
jupyter-nbextensions-configurator (0.2.2)
language-selector (0.1)
louis (2.5.3)
lxml (3.3.3)
Mako (0.9.1)
MarkupSafe (0.23)
matplotlib (1.3.1)
mistune (0.7.3)
murmurhash (0.26.4)
nbconvert (4.2.0)
nbformat (4.1.0)
nltk (3.2.1)
nose (1.3.1)
notebook (4.2.3)
numexpr (2.2.2)
numpy (1.11.2)
oauthlib (0.6.1)
onboard (1.0.1)
oneconf (0.3.7.14.4.1)
pandas (0.13.1)
pathlib (1.0.1)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (2.3.0)
pip (9.0.1)
piston-mini-client (0.7.5)
plac (0.9.6)
plainbox (0.5.3)
preshed (0.46.4)
prettytable (0.7.2)
prompt-toolkit (1.0.9)
protobuf (3.0.0b2)
psutil (5.0.0)
ptyprocess (0.5.1)
pycrypto (2.6.1)
pycurl (7.19.3)
pyflakes (0.8.1)
Pygments (2.1.3)
pygobject (3.12.0)
pyparsing (2.0.1)
python-apt (0.9.3.5ubuntu2)
python-dateutil (2.0)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2012rc0)
pyxdg (0.25)
PyYAML (3.12)
pyzmq (16.0.0)
qtconsole (4.2.1)
requests (2.2.1)
scipy (0.13.3)
semver (2.7.1)
setuptools (28.8.0)
simplegeneric (0.8.1)
six (1.10.0)
software-center-aptd-plugins (0.0.0)
spacy (1.2.0)
sputnik (0.9.3)
tables (3.1.1)
tensorflow (0.9.0rc0)
terminado (0.6)
textblob (0.11.1)
thinc (5.0.8)
tornado (4.4.2)
traitlets (4.3.1)
twitter (1.17.1)
ubuntu-drivers-common (0.0.0)
ufw (0.34-rc-0ubuntu2)
ujson (1.35)
unattended-upgrades (0.1)
unity-scope-audacious (0.1)
unity-scope-calculator (0.1)
unity-scope-chromiumbookmarks (0.1)
unity-scope-clementine (0.1)
unity-scope-colourlovers (0.1)
unity-scope-devhelp (0.1)
unity-scope-firefoxbookmarks (0.1)
unity-scope-gdrive (0.7)
unity-scope-gmusicbrowser (0.1)
unity-scope-gourmet (0.1)
unity-scope-guayadeque (0.1)
unity-scope-manpages (0.1)
unity-scope-musique (0.1)
unity-scope-openclipart (0.1)
unity-scope-texdoc (0.1)
unity-scope-tomboy (0.1)
unity-scope-virtualbox (0.1)
unity-scope-yelp (0.1)
unity-scope-zotero (0.1)
urllib3 (1.7.1)
usb-creator (0.2.23)
wcwidth (0.1.7)
wheel (0.29.0)
widgetsnbextension (1.2.6)
xdiagnose (3.6.3build2)
xkit (0.0.0)

**Comment by pint12** [comment]
i am having the same issue : 
occurring after parsing 

  File "C:\Python27\lib\site-packages\spacy\language.py", line 123, in default_parser
    return Parser.from_dir(data_dir, vocab.strings, ArcEager)
  File "spacy/syntax/parser.pyx", line 98, in spacy.syntax.parser.Parser.from_dir (spacy/syntax/parser.cpp:5759)
    
  File "thinc/linear/avgtron.pyx", line 89, in thinc.linear.avgtron.AveragedPerceptron.load (thinc/linear/avgtron.cpp:3092)
    
  File "preshed/maps.pyx", line 23, in preshed.maps.PreshMap.__init__ (preshed/maps.cpp:1200)
    
  File "preshed/maps.pyx", line 90, in preshed.maps.map_init (preshed/maps.cpp:2876)
    
  File "cymem/cymem.pyx", line 42, in cymem.cymem.Pool.alloc (cymem/cymem.cpp:1091)
    
MemoryError: Error assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytes

**Comment by sradhamadhavi** [comment]
Any Resolution for the issue stated? Even I have the same issue in Amazon instance

**Comment by mzw4** [comment]
I had the same issue - I increased the size of my ec2 instance and it resolved it.

If there is a better way, I'd love to know since it doesn't make sense to provision a larger instance just for extra memory for a startup script!
