### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [spacy-io/spaCy#290]
```
assert token.shape_ == 'Xxxxx'
for lexeme in nlp.vocab:
    if lexeme.is_alpha:
        lexeme.shape_ = 'W'
    elif lexeme.is_digit:
        lexeme.shape_ = 'D'
    elif lexeme.is_punct:
        lexeme.shape_ = 'P'
    else:
        lexeme.shape_ = 'M'
assert token.shape_ == 'W'
```

TypeError: Argument 'x' has incorrect type (expected unicode, got str)

**Comment by jesuisnicolasdavid** [comment]
ok i've found the solution, why is nobody flagging the difference between python2 and 3 in the example ?

from __future__ import unicode_literals

**Comment by henningpeters** [comment]
All examples are Python 3 or assuming `from future import unicode_literals`. We should make that clearer, thanks.
