### ISSUE TITLE
Error on example pos_tag.py 

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [spacy-io/spaCy#291]
Hi, i am trying to run the part of speech example with the reddit comment corpus and i am falling into this error. Anyone has an idea ?

AttributeError: 'spacy.tokens.token.Token' object has no attribute 'vocab'

**Comment by syllog1sm** [comment]
Thanks for the report.

Unfortunately the examples aren't being automatically tested at the moment, and that one slipped out of date. I fixed that error, but I haven't rerun it yet to make sure everything else is working.

If there's another problem let me know, and I'll go over it properly.

**Comment by jesuisnicolasdavid** [comment]
There is a function name that is not corresponding inside the code that you should modify but other than that, all is working well.

`def iter_texts(loc):`
