### ISSUE TITLE
spaCy not multiprocessing on Linux EC2 instance

### ISSUE THREAD

**Issue by gushecht** [spacy-io/spaCy#292]
Hey there!  I'm hoping to use the multiprocessing of `English.pipe`, however when I run my script and specify a value for `n_threads` that is >= 2 and check what processes are running, I only see one.  My understanding of `batch_size` and `n_threads` is that the pip will accumulate `batch_size` texts and then work on them with `n_threads` 

In my script, I have the following:
```python
def main(in_dir, out_dir, batch_size=500, n_threads=2):
    # Create the output directory, if it doesn't exist
    if not path.exists(out_dir):
        makedirs(out_dir)
    # Get total number of input files for tracking progress
    total_files = len(list(iter_dir(in_dir)))
    # Load nlp object
    print('Loading spacy.en.English, this may take a while....')
    nlp = spacy.en.English()
    print('spacy.en.English loaded!')
    # For each input file
    for i, file in enumerate(iter_dir(in_dir)):
        print('Tagging file %s of %s' % (i, total_files))
        # Create the first output file
        current_time = str(int(time.time()))
        out_loc = current_time + '_' + str(i) + '.txt'
        target = open(path.join(out_dir, out_loc), 'w')
        # Create empty string to store tagged text
        tagged_text = ''
        for j, doc in enumerate(nlp.pipe(line_iterator(file),
                                         batch_size=batch_size,
                                         n_threads=n_threads)):
            tagged_text += transform_doc(doc)
        target.write(tagged_text)
        target.close()
```

I'm running a four core EC2 Linux instance.  To set it up, I did the following:
```
sudo yum update
sudo yum groupinstall 'Development Tools'
sudo pip install spacy
sudo python -m spacy.en.download
```

Full code attached, plus sample file that I'm trying to POS Tag.

Thank you!
[633a.txt](https://github.com/spacy-io/spaCy/files/174203/633a.txt)
[merge_text.py.zip](https://github.com/spacy-io/spaCy/files/174205/merge_text.py.zip)

**Comment by henningpeters** [comment]
How do you obtain the number of threads running? Are you sure you are not looking at processes? By default commands like `top` and `ps` show processes, not threads. You can view threads, e.g., via `top -H` or by pressing `H` while running (http://unix.stackexchange.com/questions/892/is-there-a-way-to-see-details-of-all-the-threads-that-a-process-has-in-linux).

**Comment by gushecht** [comment]
Ah perhaps I've misunderstood the `English.pipe` documentation.  Clearly it does say `n_threads`, but I was hoping that the reference to OpenMP meant that it's multiple processes not threads.  Pressing H reveals that there are the expected number of threads running.

My understanding of multithreading versus multiprocessing is that the former uses a single processor and the latter uses multiple.  To be clear, the `English.pipe` spaCy object supports multithreading, but not multiprocessing?

**Comment by henningpeters** [comment]
Yes, that's by design and probably what you want to use. spaCy consumes significant amounts of memory for its models. By using multiple threads and releasing the [gil](https://wiki.python.org/moin/GlobalInterpreterLock) within `pipe()` we can scale almost linearly, see https://github.com/spacy-io/spaCy/issues/172#issuecomment-180916769.

Only once the bottleneck is memory I/O you want to use multi-processing. Here's an example with both, multi-processing and multi-threading: https://github.com/spacy-io/spaCy/blob/master/examples/parallel_parse.py.

**Comment by syllog1sm** [comment]
You should be able to see it working the processor at say, 300%. More to the point, it should be faster :)

The important difference is that with multi-threading, you don't have to load multiple copies of the model. If you use multiple processes, you can't share the memory between different workers. To fully utilise a machine, you probably want multiple processes, and then multiple threads per process.

But, we're not going to create more processes for you. That's up to you --- the best strategy of chunking up your work will depend on your problem.

**Comment by gushecht** [comment]
Got it going with multiprocessing!  Occasionally, I see a message like this, although it doesn't kill my program:
![image](https://cloud.githubusercontent.com/assets/2095663/13794867/6e22952e-eabb-11e5-9073-d0f559114263.png)

And if I re-run it, it makes it through those files successfully.

Script attached.  I'm running 31 processes, 4 threads, batch_size=100, on a single preprocessed text file with 22625069 lines, bzipped to 1.32GB.

**Comment by syllog1sm** [comment]
Not sure what the problems are, but I can tell you that `batch_size=100` is probably too small to use the multithreading very effectively. Try `batch_size=10000`.
