### ISSUE TITLE
Errors installing on OS X 10.6.8

### ISSUE THREAD

**Issue by robclewley** [spacy-io/spaCy#294]
I failed when installing with pip, including from source. I have a 32 bit Python 2.7 setup on my old Snow Leopard laptop that originated from fink. I keep it updated using pip now, and occasionally install packages with homebrew. Anyway, I usually succeed in installing python packages that need to compile C code, but spaCy is failing to create 32 bit DLLs. My usual, successful approach is `sudo "ARCHFLAGS=-arch i386" "FFLAGS=-m32" "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32" "ARCH=i386" pip install` (I later `sudo chmod` the installed packages to be accessible for all users). From the pip installer's wheel, this appears to work but when I import spacy for the first time, python complains that

ImportError: dlopen(/sw/lib/python2.7/site-packages/spacy/attrs.so, 2): no suitable image found.  Did find:
	/sw/lib/python2.7/site-packages/spacy/attrs.so: mach-o, but wrong architecture

When I try installing from source instead, using your suggested commands (minus the virtualenv part as I want to integrate this package into my mature, established set of installed packages), I get 

`    Complete output from command python setup.py egg_info:

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # Reserve 64 values for flag features
    cpdef enum attr_id_t:
         ^
    ------------------------------------------------------------

    attrs.pxd:2:6: C struct/union/enum cannot be declared cpdef
    Processing attrs.pyx
    Traceback (most recent call last):
      File "/Users/robclewley/spaCy/bin/cythonize.py", line 156, in <module>
        run(args.root)
      File "/Users/robclewley/spaCy/bin/cythonize.py", line 147, in run
        process(base, filename, db)
      File "/Users/robclewley/spaCy/bin/cythonize.py", line 113, in process
        preserve_cwd(base, process_pyx, root + '.pyx', root + '.cpp')
      File "/Users/robclewley/spaCy/bin/cythonize.py", line 78, in preserve_cwd
        func(*args)
      File "/Users/robclewley/spaCy/bin/cythonize.py", line 60, in process_pyx
        raise Exception('Cython failed')
    Exception: Cython failed
    Cythonizing sources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/robclewley/spaCy/setup.py", line 215, in <module>
        setup_package()
      File "/Users/robclewley/spaCy/setup.py", line 167, in setup_package
        generate_cython(root, 'spacy')
      File "/Users/robclewley/spaCy/setup.py", line 113, in generate_cython
        raise RuntimeError('Running cythonize failed')
    RuntimeError: Running cythonize failed

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/robclewley/spaCy`

Any ideas on how to proceed, please?

**Comment by henningpeters** [comment]
spaCy currently does not supports 32 bit, so expect a bumpy road ahead. But
that's (not yet) the issue here. The wheels are pre-built binaries for 64
bit, hence won't run on 32 bit. There is no compilation step hence your
flags are ignored.

Looking at your error: it's failing at cythonizing the sources. Could you
check whether you have an up-to-date version of cython installed? I will
also check again the minimum version of cython spaCy requires.

Alternatively you could try to compile from the source package (it does
not require cython), you can get it from
https://pypi.python.org/packages/source/s/spacy/spacy-0.100.6.tar.gz
<https://pypi.python.org/packages/source/s/spacy/spacy-0.100.6.tar.gz#md5=890ff5a1855511b38084838bbbd2bcd1>
and
install it via pip.

>

**Comment by robclewley** [comment]
Thank you for the prompt reply. My Cython is 0.19.1. I updated to 0.23 and the from-source install makes it to the end, reporting

`sudo -H "ARCHFLAGS=-arch i386" "FFLAGS=-m32" "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32" "ARCH=i386" pip install -e .
Obtaining file:///Users/robclewley/spaCy
Requirement already satisfied (use --upgrade to upgrade): numpy in /sw/lib/python2.7/site-packages (from spacy==0.100.6)
Requirement already satisfied (use --upgrade to upgrade): murmurhash<0.27,>=0.26 in /sw/lib/python2.7/site-packages (from spacy==0.100.6)
Requirement already satisfied (use --upgrade to upgrade): cymem<1.32.0,>=1.30 in /sw/lib/python2.7/site-packages (from spacy==0.100.6)
Requirement already satisfied (use --upgrade to upgrade): preshed<0.47,>=0.46.1 in /sw/lib/python2.7/site-packages (from spacy==0.100.6)
Requirement already satisfied (use --upgrade to upgrade): thinc<5.1.0,>=5.0.0 in /sw/lib/python2.7/site-packages (from spacy==0.100.6)
Requirement already satisfied (use --upgrade to upgrade): plac in /sw/lib/python2.7/site-packages (from spacy==0.100.6)
Requirement already satisfied (use --upgrade to upgrade): six in /sw/lib/python2.7/site-packages (from spacy==0.100.6)
Requirement already satisfied (use --upgrade to upgrade): ujson in /sw/lib/python2.7/site-packages (from spacy==0.100.6)
Requirement already satisfied (use --upgrade to upgrade): cloudpickle in /sw/lib/python2.7/site-packages (from spacy==0.100.6)
Requirement already satisfied (use --upgrade to upgrade): sputnik<0.10.0,>=0.9.2 in /sw/lib/python2.7/site-packages (from spacy==0.100.6)
Requirement already satisfied (use --upgrade to upgrade): semver in /sw/lib/python2.7/site-packages (from sputnik<0.10.0,>=0.9.2->spacy==0.100.6)
Installing collected packages: spacy
  Running setup.py develop for spacy
Successfully installed spacy`

(sorry, I don't know why the code markdown doesn't retain the EOLs)

However, on importing (after the chmod in site-packages), I get 
`ImportError                               Traceback (most recent call last)
<ipython-input-1-c080f6458562> in <module>()
----> 1 import spacy

/Users/robclewley/spaCy/spacy/__init__.py in <module>()
----> 1 from . import util
      2 from .en import English
      3
      4
      5 def load(name, vectors=None, via=None):

/Users/robclewley/spaCy/spacy/util.py in <module>()
     12
     13 from . import about
---> 14 from .attrs import TAG, HEAD, DEP, ENT_IOB, ENT_TYPE
     15
     16

ImportError: No module named attrs`

I also noticed that only `spacy.egg-link` was created in my site-packages, which is a file that simply lists my `/Users/robclewley/spaCy` folder and `.`. Is that right?

**Comment by henningpeters** [comment]
Yep, if you install with -e pip creates this egg-link file which
essentially tells python to include your spaCy source dir in its path.

What happens if you simply install without any flags? They are not needed
and might do more harm than good.

Compilation under 32 bit should work (did you ever tried simply pip install
spacy?), but you'll get memory errors when running spaCy.

Also I'd like to ask you to repeat that in a virtualenv. It's really not a
good practice to install via sudo for numerous reasons, better helping
you debug your installation is one of them :-)


Am Mittwoch, 16. März 2016 schrieb Robert Clewley :

**Comment by robclewley** [comment]
Oh, right, I see about the `-e`. Reinstalling these dependencies and using the source package link you listed I seem to have it working now. I still needed the flags to force it to make a 32 bit build, otherwise I get similar architecture mismatch errors. For whatever reason, my fragile old system (think of it as Mr Burns) has long needed sudo + the flags to make anything work, and I don't want to fix what's technically not broken until I get a brand new machine. Also, virtualenv doesn't help me integrate my project work using scrapy with several other large packages with complex dependencies that I already have installed on my system, unless I'm misunderstanding how to use it.

In any case, thanks for your help, as it now works!
