### ISSUE TITLE
Phrasal Verb Detection in Dependency Parsing

### ISSUE THREAD

**Issue by aria-omidvar** [spacy-io/spaCy#297]
First of all, many thanks for your great toolkit. It's doing a great job.
We were using spaCy dependency parser for detecting phrasal verbs that my colleague found out that the parser takes two-word adjectives with a "-" in between like "stand-up" or "sold-out" as phrasal verbs too.
In my program I filtered them out later myself, but I assumed you want to improve the precision of spaCy dependency parser as well.
Needless to say, above-mentioned structures can't be phrasal verbs under any circumstances.

**Comment by brandoncarl** [comment]
@aria-omidvar very cool on the phrasal verbs? Would you mind discussing a bit more how you're achieving this in spaCy? I'm running into these very problems at the moment.

**Comment by aria-omidvar** [comment]
I'm terribly sorry for my late reply @brandoncarl .
here's a sample code:

def phrasal_verb_recognizer() :

    for sentence in nltk.sent_tokenize(newsText) :

        parsed = parser(sentence)#parse the sentence

        for token in parsed :
            if token.dep_ == "prt" and token.head.pos_ == "VERB" :
                verb = token.head.orth_
                particle = token.orth_

as you can see, we parse a sentence and look for the dependency "prt" and PoS "VERB" for the token's head. it seems to be better to disregard the PoS of the token itself.

I hope it helps.

**Comment by brandoncarl** [comment]
Yes that is, thank you!
