### ISSUE TITLE
Cannot install spaCy for Pyth2.7 (64-bit) on Win10

### ISSUE THREAD

**Issue by HactarCE** [spacy-io/spaCy#298]
I'm using Python 2.7 64-bit on Windows 10 64-bit. Pip is up-to-date, however "pip install spacy" returns this: http://pastebin.com/F8Bd4hfB

Looking through some of the other issues on here, I saw that you were developing a "wheel" installer, so (through some simple URL manipulation) I tried to download a wheel file for Python 2.7, but that returned this error: http://pastebin.com/16WCPCk9

I have been trying for almost a week now to install spaCy, and really cannot continue development without it. Thank you very much for the help. :)

**Comment by henningpeters** [comment]
Sorry that installing spaCy was such a waste of time for you, in fact its a
top priority for us to make installing spaCy as simple and straight-forward
as possible. Unfortunately, Python packaging is in a bit of a messy state
and makes it hard, but we are pretty close.

The error (both are the same) you get is easy to decipher though once
you've seen it before: setuptools/distutils didn't find a proper compiler
environment.

In case of Python 2.7 you need Visual Studio 2008 (free express edition
works), the 64 bit version of the compiler suite (comes as part of Windows
SDK) and a stdint.h header that MS forgot to ship. That's nothing specific
to spaCy, but required for all Python packages with C extensions.

Once we have wheels for spaCy and all dependencies (currently only
spaCy and thinc) you won't need to compile anything anymore. All future
releases will ship as wheels, hence it won't take long anymore.

If you can't wait for full wheels coverage and don't want to configure the
compiler setup I recommend you take a look at our binary conda packages
on the spacy channel (conda install -c spacy spacy).they are kept in sync
with the latest pypi releases.

Am Freitag, 18. März 2016 schrieb Hactar :

**Comment by HactarCE** [comment]
Thank you very much! I'm glad you're working on this issue. SpaCy appears to be working 100% now. :)

**Comment by henningpeters** [comment]
Update: We are now shipping `stdint.h` together with spaCy, see https://github.com/spacy-io/spaCy/tree/master/include/msvc9
