### ISSUE TITLE
Pickle file load error

### ISSUE THREAD

**Issue by JimmyMcNullty** [spacy-io/spaCy#299]
Model files for deps, ner, and pos are giving invalid load key or EOF error when I try to load them using pickle. I have run it on windows and linux systems. I don't think it is a binary mode transfer issue. I have checked it in detail. I am not able to figure out the issue.

**Comment by syllog1sm** [comment]
I think there might be some misunderstanding here. What code are you trying to execute?

If you're trying to do something like

    with open('pos/model') as file_:
        deps_model = pickle.load(file_)

then no, that won't work. That's not a pickle file, it's an internally defined binary data file, designed for fast loading and memory efficiency.

**Comment by JimmyMcNullty** [comment]
Can you post the code please? It is not working.

**Comment by syllog1sm** [comment]
Code to do what?
 
    import spacy.en
    nlp = spacy.en.English()

will load the models.
