### ISSUE TITLE
Dependency Parsing

### ISSUE THREAD

**Issue by MahaRaafat** [spacy-io/spaCy#301]
I am trying to use this example from your blog :
parser = parser.Parser()
tokens = "Set the volume to zero when I 'm in a meeting unless John 's school calls".split()
>>> tags, heads = parser.parse(tokens)
>>> heads
[-1, 2, 0, 0, 3, 0, 7, 5, 7, 10, 8, 0, 13, 15, 15, 11]
>>> for i, h in enumerate(heads): 
...   head = tokens[heads[h]] if h >= 1 else 'None'
...   print(tokens[i] + ' <-- ' + head])

It keeps getting me error 
  parser = parser.Parser()
NameError: name 'parser' is not defined

**Comment by henningpeters** [comment]
You probably refer to the example in [this post](https://spacy.io/blog/parsing-english-in-python), right? If you read the article carefully you'll notice that it talks about writing your own parser in 500 lines of code. Its this parser for which the example code is meant, not spaCy. Please take a look at the spaCy docs for guidance on how to use spaCy.
