### ISSUE TITLE
IOError: when use nlp=English(data_dir=data_dir)

### ISSUE THREAD

**Issue by wxyyxc1992** [spacy-io/spaCy#303]
when i use : 
```
nlp = English()
```
it works well,but when i set the data_dir params, it reports IOError:
```
data_dir = os.environ.get('SPACY_DATA', LOCAL_DATA_DIR)
nlp = English(data_dir=data_dir)
```
```
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-20-d41df14def99> in <module>()
----> 1 nlp = English(data_dir=data_dir)

/Users/apple/anaconda/envs/word2vec/lib/python2.7/site-packages/spacy/language.pyc in __init__(self, data_dir, vocab, tokenizer, tagger, parser, entity, matcher, serializer, load_vectors, package, vectors_package)
    237         self.tokenizer = tokenizer
    238         if tagger in (None, True):
--> 239             tagger = Tagger.from_package(package, self.vocab)
    240         self.tagger = tagger
    241         if entity in (None, True):

/Users/apple/anaconda/envs/word2vec/lib/python2.7/site-packages/spacy/tagger.pyx in spacy.tagger.Tagger.from_package (spacy/tagger.cpp:5102)()
    159         model = TaggerModel(templates)
    160         if pkg.has_file('pos', 'model'):
--> 161             model.load(pkg.file_path('pos', 'model'))
    162         return cls(vocab, model)
    163 

/Users/apple/anaconda/envs/word2vec/lib/python2.7/site-packages/thinc/linear/avgtron.pyx in thinc.linear.avgtron.AveragedPerceptron.load (thinc/linear/avgtron.cpp:3120)()
     89         self.weights = PreshMap(reader.nr_feat)
     90         cdef int i = 0
---> 91         while reader.read(self.mem, &feat_id, &feature):
     92             self.weights.set(feat_id, feature)
     93             if i % 1000 == 0:

/Users/apple/anaconda/envs/word2vec/lib/python2.7/site-packages/thinc/linear/serialize.pyx in thinc.linear.serialize.Reader.read (thinc/linear/serialize.cpp:2616)()
    100         if status < 1:
    101             if errno:
--> 102                 PyErr_SetFromErrno(IOError)
    103             return 0  # end of file
    104 
```
i use 0.100.6

**Comment by syllog1sm** [comment]
Thanks for the report. We've noticed this too today, and it's puzzling us. I think the choice of `IOError` might be misleading here. It looks to me like the file exists, but that there's some formatting problem, possibly introduced when we were working on the perceptron code to reduce the model loading time.

We'll keep you posted.

**Comment by syllog1sm** [comment]
Just pushed thinc 5.0.7, which should have this fixed. Try

    pip install --upgrade thinc

And let me know whether you still have problems.

**Comment by acquayefrank** [comment]
@syllog1sm   I tried pip install --upgrade thinc but I still get the IOError

**Comment by henningpeters** [comment]
I think I figured out what's wrong here. `spacy.en.LOCAL_DATA_DIR` is deprecated (see https://github.com/spacy-io/spaCy/blob/master/spacy/en/__init__.py#L036) and points to the old data directory `spacy/en/data`.

It seems you still have some old files lying around there even though they should have been migrated by a run of `python -m spacy.en.download`. On a fresh install I also get an `IOError`, but about not being able to find the model files, not a thinc loading error.

Could you please try the following:

```
import spacy
from spacy.en import English
import sputnik
pkg = sputnik.package(spacy.about.__title__, spacy.about.__version__, 'en')
nlp = English(data_dir=pkg.path)
```

`data_dir` points to a model directory. In this sample we construct it via sputnik from the installed package, but normally you would use this parameter when you have the model files stored outside the spacy directory.

I hope that helped. Sorry, some code and docs might have not been kept up to date. Any pointers to outdated information is greatly appreciated.
