### ISSUE TITLE
Twitter Tutorial Gives 404 Error

### ISSUE THREAD

**Issue by newterminator** [spacy-io/spaCy#317]
Wanted to notify that the Twitter Tutorial as mentioned in the Spacy [docs](https://spacy.io/docs#tutorials) gives a [404 error](https://spacy.io/tutorials/twitter-filter).

**Comment by honnibal** [comment]
Hey,

Thanks for reporting.

The docs have been reformatted for the new website, and the tutorials are moved under the docs. Is there an old link somewhere? The ones on spacy.io/docs/ look okay to me.

**Comment by newterminator** [comment]
Hey @honnibal Thanks for mentioning that the site was re-organised. Had to hit refresh on the site to see the new links and layout. Thanks for the awesome work on Spacy btw.
