### ISSUE TITLE
Trouble using spaCy on Travis

### ISSUE THREAD

**Issue by suchow** [spacy-io/spaCy#318]
I've created a minimal example of trying to install spaCy on Travis (https://github.com/suchow/spacy-test). It leads to the following error (https://travis-ci.org/suchow/spacy-test/jobs/120367697):

```
from .tokenizer import Tokenizer
File ".env/local/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd", line 155, in init spacy.tokenizer (spacy/tokenizer.cpp:10076)
ValueError: numpy.dtype has the wrong size, try recompiling
```

Any idea what's going on?

**Comment by honnibal** [comment]
Well, here's our travis.yml: https://github.com/spacy-io/spaCy/blob/master/.travis.yml

Not entirely sure why this should be different. I can't test this just now, but I'll come back to it tonight unless someone else gets to it first.

**Comment by henningpeters** [comment]
It looks like the numpy with which we built spaCy is newer than the numpy version installed on travis. Simple solution: upgrade numpy on travis (see https://github.com/henningpeters/spacy-test and https://travis-ci.org/henningpeters/spacy-test). It's not your fault though; we didn't properly enforce the numpy version on our end during packaging. I will make sure that future spaCy release will be built with the oldest possible numpy version.

Numpy developers generally make sure that the library's binary interface is backward-compatible. Here's a good explanation from the numpy developer perspective: http://stackoverflow.com/questions/17709641/valueerror-numpy-dtype-has-the-wrong-size-try-recompiling/18369312#18369312

**Comment by suchow** [comment]
This works now, thanks!
