### ISSUE TITLE
Downloading language model from within .py, Is there a __version__ of language model?

### ISSUE THREAD

**Issue by apiszcz** [spacy-io/spaCy#319]
Another option to invoke the download(sputnik)
from spacy.en import download
download.main()
or 
download.main(force=True)

Is there an API method to determine the version or release date of the language model?
I see the version name is 1.0.9 on the folder, is there an API call to determine the same?
Is there an announcement or location to review the latest available language model?

**Comment by henningpeters** [comment]
Yes, that's possible via `sputnik`, a separate library that abstracts data model management for spacy and similar projects. Try this code (sorry, docs are not great, but here's an overview: https://github.com/spacy-io/sputnik):

```
import spacy
import sputnik
pkg = sputnik.package(spacy.about.__title__, spacy.about.__version__, 'en')
print(pkg.name, pkg.version)
```

The first two parameters, `spacy.about.__title__` and `spacy.about.__version__` are for telling sputnik about spacy and its version. The third parameter, `'en'`, specifies the model. You can also add version constraints, e.g., `en>=1.0.0`. Note that the model needs to be installed before being queried in this way.

Also check out the download script to see how you can install models directly via sputnik: https://github.com/spacy-io/spaCy/blob/master/spacy/download.py, in short:

```
import spacy
import sputnik
sputnik.install(spacy.about.__title__, spacy.about.__version__, 'en')
```

**Comment by henningpeters** [comment]
For obtaining a package path use:

```
import spacy
import sputnik
pkg = sputnik.package(spacy.about.__title__, spacy.about.__version__, 'en')
pkg.path
```

For obtaining the latest `en` model please run `python -m spacy.en.download`. Until now we didn't announce model updates, but plan to do so in the future. Specifically for those and other announcements we created a newsletter. You can subscribe to it on the website (scroll down to the end): https://spacy.io
