### ISSUE TITLE
Named Entities ending with s are being lemmatized

### ISSUE THREAD

**Issue by henningko** [spacy-io/spaCy#325]
Named entities ending with `s` will be treated by the lemmatizer as if they are plurals, e.g.
`Bernie Sanders` turns into `bernie sander`, `ISIS` becomes `isi`, `United States` becomes `united state`. It probably also applies to other suffixes.

This _may_ be intentional, so maybe adding a flag would be a good solution. Or is there another work around?

[Update] Somewhat related: when something like `CIA` is at the end of a sentence, the named entity becomes `CIA.`. My guess is that this is done to account for acronyms like `A.M.`, [but the trend seems to be to eliminate periods from acronyms](https://en.wikipedia.org/wiki/Acronym#Punctuation), so punctuation can probably be stripped from the Named Entity altogether (avoiding the inconsistency).

**Comment by honnibal** [comment]
Thanks for the report. Will add tests and fix.

**Comment by honnibal** [comment]
This should be fixed in the next release of the data. There are some details in the associated commit. Thanks for the repot!
