### ISSUE TITLE
displacy source code / docs

### ISSUE THREAD

**Issue by kengz** [spacy-io/spaCy#330]
Is the source code for [displacy](https://spacy.io/demos/displacy) open. Would love to see the function and docs for generating the result on the site, apart from having to dig into the HTML source and decipher from there.

**Comment by henningpeters** [comment]
Sorry, no, we haven't open sourced the current version of displacy. I believe there is an older version of both client and server buried in spaCy's history though. Are you just curious how its written or do you have some use-case in mind beyond that.

**Comment by kengz** [comment]
That's alright. I can write my own, just thought if it's available I don't have to reinvent the wheel. I'm using it for knowledge base creation and bot command parsing.

- Knowledge base creation is straight forward: entities as nodes, non-entitties as edges.
- command parsing is a little more complicated: one has to identify intent, then the needed arguments for the command, but the dependency parsing will help a lot.

**Comment by henningpeters** [comment]
Nice, would love to see the results once you're finished with it.

What about just licensing it from us instead of reinventing the wheel? You would also help keeping our lights on. If that sounds feasible please send me a mail to hp@spacy.io.

Btw: did you already see @inesmontani's post about displacy at https://ines.io/blog/developing-displacy?

**Comment by kengz** [comment]
I'll prolly make it return a simple json of the tree, seems to be the natural choice for various applications.

Licensing what from u guys?

**Comment by honnibal** [comment]
To clarify a little bit, we really think of displacy as the front-end code. We haven't open-sourced the server code, but you're right to say that it's fairly trivial (and actually, very tightly coupled to the requirements of the front-end --- the two were designed jointly.)

We wrote the displacy visualiser so that we could explain the syntactic annotations to people, and to make it easy to see how spaCy annotated a given sentence. The syntactic annotation scheme is made up of arbitrary labellings, so you need to see examples to write rules etc. We also plan to make an annotation tool based on this type of interface. If you want to use the code as a visualiser or an annotation tool, it might make sense to license the code from us.

Do you just want to make a REST service that serves JSON structures from spaCy's parses? This isn't very difficult to do, and we should probably have a to_json() method on the `Doc` object. But, we don't currently, partly because it's easy and very application dependent.

**Comment by kengz** [comment]
Hey, @honnibal ! I'm planning to add a wrapper method in python to do the parsing and extract the equivalent of the parse tree. Nothing fancy, just so that one does not have to manually get lefts, rights, root etc. of the tree - like you said, pretty much adding the to_json() method (not a REST service). I was planning on submitting a PR in case anyone was interested in using it as well.

I'm familiar with spaCy and its MIT-license; I wasn't sure if displaCy fell under that. I opened this issue as I was curious whether there's an open repo of displaCy out there, otherwise I was going to write my own and open source it. Happy to share the code either way.

It was mentioned that there might be a way of "licensing it from us". Any place I can find more detail?

**Comment by honnibal** [comment]
We don't have a page to link you to about licensing the displacy code, no --- it's probably best to switch to email for this. I have to say I'm still sort of confused about what you're trying to do!

**Comment by kengz** [comment]
hah sorry for the confusion. Here's what I meant to do:

```python
def tag_filter(doc):
  ents = doc.ents
  index = 0
  res = []
  for e in ents:
    while index < e.start:
      # skip the tokens that are in NER tags
      res.append( (doc[index].text, doc[index].pos_) )
      index = index + 1
    res.append( (e.text, e.label_) )
    index = e.end # reset by skipping
  # keep iterating till len(doc)
  while index < len(doc):
    res.append( (doc[index].text, doc[index].pos_) )
    index = index + 1
  return res

s = "displaCy uses CSS AND JavaScript to show you how computers understand language."
doc = nlp(s)
```

and so
```python
tag_filter(doc)
```

would return the *flat* result of the displaCy page, i.e. tags without tree structure
```python
[('displaCy', 'PRODUCT'), ('uses', 'VERB'), ('CSS', 'PRODUCT'), ('AND', 'CONJ'), ('JavaScript', 'PRODUCT'), ('to', 'PART'), ('show', 'VERB'), ('you', 'NOUN'), ('how', 'ADV'), ('computers', 'NOUN'), ('understand', 'VERB'), ('language', 'NOUN'), ('.', 'PUNCT')]
```

As for producing the edges, e.g. `ccomp` and so on, does spaCy return those? I haven't found out a way to get them.

A way to make the tree into JSON would be passing the `list(doc.sents[0].root)` into the following:
```python
def gen_tree(root):
  subtree = {
    root.text: {
      "edge_from_parent": <ccomp, nobj etc.>
      "lefts": [],
      "rights": []
    }
  }
  lefts = list(root.lefts)
  rights = list(root.rights)
  for l in lefts:
    subtree[root.text]["lefts"].append(gen_tree(l))
  for r in rights:
    subtree[root.text]["rights"].append(gen_tree(r))
  return subtree
```

Of course that last function isn't complete yet. I wish for it to produce the full result of displaCy, i.e. the flat tags with the edges, in a JSON structure. So this'll be a wrapper method that people can use.

**Comment by kengz** [comment]
Here's the use case I'm aiming at: for example a bot that helps you find flights can use it:

```python
s = "find me flights from New York to London next month"
tag_filter(nlp(s))
# returns [('find', 'VERB'), ('me', 'NOUN'), ('flights', 'NOUN'), ('from', 'ADP'), ('New York', 'GPE'), ('to', 'ADP'), ('London', 'GPE'), ('next month', 'DATE')]
```
With the dependency tree (and labeled edges), it would be able to accurately pick up the needed info in a flexible manner, i.e. I can rephrase however I wish and it will still work.

**Comment by honnibal** [comment]
What does this have to do with the front-end, though? What you're doing here is using spaCy to get the syntactic parse, and then walking the tree and transforming it. That's totally normal usage of the library. The displaCy code is HTML/CSS/JS to make the parse display nicely, and to allow you to step through the parser, so you can understand it better.

**Comment by kengz** [comment]
Nothing to do with the front end, I guess that was the confusion there, sorry for that :)
I was just hoping to write a wrapper function that outputs the parse tree seen on the website.

`token.dep_` is what I need! Thanks a lot. Let's consider this resolved.

**Comment by kengz** [comment]
Finished the implementation [here](https://github.com/kengz/aiva/blob/aiva-v3/lib/py/nlp.py#L97) for anyone who wishes to use it.
