### ISSUE TITLE
error with spacy.en.download import error

### ISSUE THREAD

**Issue by tachee** [spacy-io/spaCy#334]
running python -m spacy.en.download fails.

I run:

c:\users\tachee\appdata\local\programs\python\python35\python -m spacy.en.download

and get the following error:

c:\users\tachee\appdata\local\programs\python\python35\python.exe: Error while finding spec for 'spacy.en.download' (<class 'ImportError'>: DLL load failed: The specified module could not be found.)

**Comment by henningpeters** [comment]
It looks like spaCy is not properly installed or what happens if you run `python -c "import spacy"`? How did you install spaCy?

**Comment by tachee** [comment]
python -c "import spacy" gives me:

C:\Users\tachee\AppData\Local\Programs\Python\Python35>python -c "import spacy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\tachee\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\__init__.py", line 2, in <module>
    from .en import English
  File "C:\Users\tachee\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\en\__init__.py", line 5, in <module>
    from ..language import Language
  File "C:\Users\tachee\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\language.py", line 11, in <module>
    from .tokenizer import Tokenizer
ImportError: DLL load failed: The specified module could not be found.

I installed using pip3.  It reported everything successful. re-installing gives me:

C:\Users\tachee\AppData\Local\Programs\Python\Python35\Scripts>pip3 install spacy
Requirement already satisfied (use --upgrade to upgrade): spacy in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): thinc in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): six in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): sputnik in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): ujson in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): cymem in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): cloudpickle in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): plac in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): murmurhash in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): preshed in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): semver in c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (from sputnik->spacy)

**Comment by henningpeters** [comment]
That's odd. It seems spaCy is installed, but the DLLs are missing. My best guess is that the installation didn't fully complete for some reason. It would be great to have the original install logs, you should be able to obtain them by uninstall all dependencies with native extensions and then re-installing spacy:

```
pip uninstall -y spacy thinc cymem murmurhash preshed ujson
pip install spacy
```

Could you please try that and share the output?

**Comment by tachee** [comment]
c:\Users\tachee\AppData\Local\Programs\Python\Python35\Scripts>pip3
uninstall -y
 spacy thinc cymem murmurhash preshed ujson
Uninstalling spacy-0.100.6:
  Successfully uninstalled spacy-0.100.6
Uninstalling thinc-5.0.7:
  Successfully uninstalled thinc-5.0.7
Uninstalling cymem-1.31.1:
  Successfully uninstalled cymem-1.31.1
Uninstalling murmurhash-0.26.2:
  Successfully uninstalled murmurhash-0.26.2
Uninstalling preshed-0.46.3:
  Successfully uninstalled preshed-0.46.3
Uninstalling ujson-1.35:
  Successfully uninstalled ujson-1.35

c:\Users\tachee\AppData\Local\Programs\Python\Python35\Scripts>pip install
spacy

Collecting spacy
  Using cached spacy-0.100.6-cp35-none-win_amd64.whl
Requirement already satisfied (use --upgrade to upgrade): numpy in
c:\users\tach
ee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Collecting murmurhash<0.27,>=0.26 (from spacy)
  Using cached murmurhash-0.26.2-cp35-none-win_amd64.whl
Collecting ujson (from spacy)
  Using cached ujson-1.35.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in
c:\users\tachee
\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Collecting thinc<5.1.0,>=5.0.0 (from spacy)
  Using cached thinc-5.0.7-cp35-none-win_amd64.whl
Requirement already satisfied (use --upgrade to upgrade):
sputnik<0.10.0,>=0.9.2
 in
c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (fr
om spacy)
Requirement already satisfied (use --upgrade to upgrade): plac in
c:\users\tache
e\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Collecting preshed<0.47,>=0.46.1 (from spacy)
  Using cached preshed-0.46.3-cp35-none-win_amd64.whl
Collecting cymem<1.32.0,>=1.30 (from spacy)
  Using cached cymem-1.31.1-cp35-none-win_amd64.whl
Requirement already satisfied (use --upgrade to upgrade): cloudpickle in
c:\user
s\tachee\appdata\local\programs\python\python35\lib\site-packages (from
spacy)
Requirement already satisfied (use --upgrade to upgrade): semver in
c:\users\tac
hee\appdata\local\programs\python\python35\lib\site-packages (from
sputnik<0.10.
0,>=0.9.2->spacy)
Building wheels for collected packages: ujson
  Running setup.py bdist_wheel for ujson ... error
  Complete output from command
c:\users\tachee\appdata\local\programs\python\pyt
hon35\python.exe -u -c "import setuptools,
tokenize;__file__='C:\\Users\\tachee\
\AppData\\Local\\Temp\\pip-build-hgrr03b6\\ujson\\setup.py';exec(compile(getattr
(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__,
'exec
'))" bdist_wheel -d
C:\Users\tachee\AppData\Local\Temp\tmpbb7o4tonpip-wheel- --p
ython-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  error: Unable to find vcvarsall.bat

  ----------------------------------------
  Failed building wheel for ujson
  Running setup.py clean for ujson
Failed to build ujson
Installing collected packages: murmurhash, ujson, cymem, preshed, thinc,
spacy
  Running setup.py install for ujson ... error
    Complete output from command
c:\users\tachee\appdata\local\programs\python\p
ython35\python.exe -u -c "import setuptools,
tokenize;__file__='C:\\Users\\tache
e\\AppData\\Local\\Temp\\pip-build-hgrr03b6\\ujson\\setup.py';exec(compile(getat
tr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'),
__file__, 'ex
ec'))" install --record
C:\Users\tachee\AppData\Local\Temp\pip-e1p72o2k-record\i
nstall-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'ujson' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "c:\users\tachee\appdata\local\programs\python\python35\python.exe
-u -c
 "import setuptools,
tokenize;__file__='C:\\Users\\tachee\\AppData\\Local\\Temp\
\pip-build-hgrr03b6\\ujson\\setup.py';exec(compile(getattr(tokenize,
'open', ope
n)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install
--record
C:\Users\tachee\AppData\Local\Temp\pip-e1p72o2k-record\install-record.txt
--sing
le-version-externally-managed --compile" failed with error code 1 in
C:\Users\ta
chee\AppData\Local\Temp\pip-build-hgrr03b6\ujson\

c:\Users\tachee\AppData\Local\Programs\Python\Python35\Scripts>pip3 install
C:\U
sers\tachee\Downloads\ujson-1.35-cp35-none-win_amd64.whl
Processing c:\users\tachee\downloads\ujson-1.35-cp35-none-win_amd64.whl
Installing collected packages: ujson
Successfully installed ujson-1.35

c:\Users\tachee\AppData\Local\Programs\Python\Python35\Scripts>pip3 install
spac
y
Collecting spacy
  Using cached spacy-0.100.6-cp35-none-win_amd64.whl
Requirement already satisfied (use --upgrade to upgrade):
murmurhash<0.27,>=0.26
 in
c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (fr
om spacy)
Requirement already satisfied (use --upgrade to upgrade): plac in
c:\users\tache
e\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade):
sputnik<0.10.0,>=0.9.2
 in
c:\users\tachee\appdata\local\programs\python\python35\lib\site-packages (fr
om spacy)
Requirement already satisfied (use --upgrade to upgrade): six in
c:\users\tachee
\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Requirement already satisfied (use --upgrade to upgrade): numpy in
c:\users\tach
ee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Collecting cymem<1.32.0,>=1.30 (from spacy)
  Using cached cymem-1.31.1-cp35-none-win_amd64.whl
Requirement already satisfied (use --upgrade to upgrade): ujson in
c:\users\tach
ee\appdata\local\programs\python\python35\lib\site-packages (from spacy)
Collecting thinc<5.1.0,>=5.0.0 (from spacy)
  Using cached thinc-5.0.7-cp35-none-win_amd64.whl
Requirement already satisfied (use --upgrade to upgrade): cloudpickle in
c:\user
s\tachee\appdata\local\programs\python\python35\lib\site-packages (from
spacy)
Collecting preshed<0.47,>=0.46.1 (from spacy)
  Using cached preshed-0.46.3-cp35-none-win_amd64.whl
Requirement already satisfied (use --upgrade to upgrade): semver in
c:\users\tac
hee\appdata\local\programs\python\python35\lib\site-packages (from
sputnik<0.10.
0,>=0.9.2->spacy)
Installing collected packages: cymem, preshed, thinc, spacy
Successfully installed cymem-1.31.1 preshed-0.46.3 spacy-0.100.6 thinc-5.0.7

**Comment by tachee** [comment]
Installing MS Visual Studio 2015 Community Edition seems to have fixed this.

**Comment by henningpeters** [comment]
Makes sense, as of now `ujson` is the only missing library in the set of spaCy dependencies that doesn't ship as precompiled binary, hence you still need a working build environment (compiler and Python headers).

**Comment by sks1996** [comment]
python -m spacy download en

this will work
