### ISSUE TITLE
Question: using pre-tokenized text

### ISSUE THREAD

**Issue by amir-zeldes** [spacy-io/spaCy#335]
Hi, 

(not sure this is the right place to ask but the docs say to use the issue tracker)

I'm trying to use spacy on pre-tokenized text, using for example white-space or one token per line. I've tried things like this:

```
from spacy.en import English
nlp = English(tokenizer=None)
```

And similarly tokenizer=False, both of which don't seem to work. I've also tried setting tokenizer to my own function which does a naive split, but I'm having trouble returning the necessary Doc object instead of just a list of strings. Is there a recommended way to force spacy to use a certain tokenization? If not, is there a good way to make a custom tokenizer function which generates a simple Doc object containing just the split-based tokens?

Thanks,
Amir

**Comment by honnibal** [comment]
There's a gap in the docs here. The method you need is `nlp.tokenizer.tokens_from_list`

**Comment by amir-zeldes** [comment]
Works like a charm, thanks! It would be great if this could be added to the docs.

**Comment by syllog1sm** [comment]
Started a tutorial page to address this type of functionality: http://staging.spacy.io/docs/tutorials/byo-annotations

Still need to add some of these methods in the API docs, and the tutorial page isn't so satisfying yet. But it'll be easier to improve once it's up.
