### ISSUE TITLE
Tokenization white space and contractions

### ISSUE THREAD

**Issue by masscognition** [spacy-io/spaCy#340]
I'm using spacy as a pre-processor for Gensim LDA analysis.

The string "can't won't couldn't don't" is tokenized, using the orth_ property of the token, as

ca
n't
wo
n't
could
n't
do
n't

Each line represents a token.
Removing the ' doesn't make any difference. The orth_ property is defines as:

"The form of the word with no string normalization or processing, as it appears in the string, without trailing whitespace."

Am I missing something ? It would also be useful if I could turn off the tokenizing of white space i.e. multiple spaces and new lines, there have no relevance in topic analysis.

many thanks

**Comment by Terrilocks** [comment]
If I may jump in: 
It has long been a convention in NLP to split contractions into their 2 word parts. "can't" is generally equivalent to "can not" so they should be treated the same.

Regarding whitespace tokenizing, I likewise am not really a fan, so get around it by recursively replacing all sequences of two or more adjacent whitespace in my texts with a single whitespace char.

**Comment by honnibal** [comment]
It's generally quite hard to describe policies in the documentation, and I haven't always done a great job, particularly for audiences that aren't already familiar with NLP.

Are you surprised that the tokenizer is splitting contractions like "can't" into "ca" and "n't"? This behaviour is dictated by a data file, so you can quite easily load a different policy. If you really just need whitespace tokenization, and don't care about maintaining alignment with the original string, maybe you'll be better off implementing a tokenizer that looks like this:

```python

class RegexTokenizer(spacy.tokenizer.Tokenizer):
    def __call__(self, string):
        pieces = self.split_string(string)
        return self.tokens_from_list(pieces)
    
    def split_string(self, string):
        # TODO
        return string.split()
```

Note that if you change the tokenization significantly, the subsequent tagging and parsing models basically won't work --- they'll have never seen a token "can't", so they won't know how to tag it.

**Comment by masscognition** [comment]
Thanks for the replies. @Terrilocks, I understand what you say, but the documentation says for orth_:

"The form of the word with **no string normalization or processing**, **as it appears in the string, without trailing whitespace.:**

To me this implies that I should get back what was in the raw string unprocessed in any way. Clearly not the case.

@honnibal Thanks for the explanation. I do need alignment of lemmas with the original string, it's trivial for me to strip out the whitespace for the input to Gensim. I take the point about lossless tokenization however. I agree that pre-processor functions would be a waste of effort.
