### ISSUE TITLE
spacy.load('en', vectors='en_glove_cc_300_1m_vectors') not working after upgrading spacy

### ISSUE THREAD

**Issue by suraj-deshmukh** [spacy-io/spaCy#345]
I have upgrade spacy to the latest version i.e 0.100.6 but i am facing problem to 

    spacy.load('en', vectors='en_glove_cc_300_1m_vectors')

this function. 
also i have installed below two dependencies
sputnik --name spacy install en 
sputnik --name spacy install en_glove_cc_300_1m_vectors

error :- 
**IndexError: -1046967279**

**Comment by henningpeters** [comment]
Please install the `en` model with `python -m spacy.en.download`, otherwise it's not guaranteed that the model you download is compatible with the spaCy version you have.

**Comment by iqbal-chowdhury** [comment]
Hi, I am getting this error while trying to load en_glove_cc_300_1m_vectors
RuntimeError: Language not supported: en_glove_cc_300_1m_vectors
