### ISSUE TITLE
Token offsets wrong after leading spaces

### ISSUE THREAD

**Issue by tobigue** [spacy-io/spaCy#351]
When analyzing a text with leading spaces the offsets of the tokens are off by 1.

Example:

    from spacy.en import English
    english_spacy = English()

    # this works

    text1 = u"This is a cat."
    a = english_spacy(text1)

    tok0 = list(a.sents)[0][0]
    print tok0, tok0.idx, text1[tok0.idx]

    tok1 = list(a.sents)[0][1]
    print tok1, tok1.idx, text1[tok1.idx]

    print "=="

    # this does not work

    text2 = u"   This is a cat."
    b = english_spacy(text2)

    tok0 = list(b.sents)[0][0]
    print tok0, tok0.idx, text2[tok0.idx]

    tok1 = list(b.sents)[0][1]
    print tok1, tok1.idx, text2[tok1.idx]

Output:

    This 0 T
    is 5 i
    ==
       0  
    This 2  

In the second example with the 3 leading spaces the index of the second token "This" should be 3, not 2.

**Comment by honnibal** [comment]
Thanks! Will fix.
