### ISSUE TITLE
Check equality of Lexemes

### ISSUE THREAD

**Issue by bwegge** [spacy-io/spaCy#361]
How to check if two lexemes are equal? I get the following behaviour, which I find odd:

```
cat1 = nlp.vocab['cat']

cat2 = nlp.vocab['cat']

cat1 == cat2

False
```

I think `cat1.orth == cat2.orth` would work, but then one still cannot add Lexemes to sets, dicts, etc.

**Comment by honnibal** [comment]
Thanks! Fixed. In the meantime you can do `cat1.orth == cat2.orth`

**Comment by bwegge** [comment]
That was quick, many thanks!

One more question regarding the fix: for `isinstance(other, str)`, shouldn't it be `a = self.orth_` (orth with underscore)?
