### ISSUE TITLE
ArcEager Break transition doesn't work as expected

### ISSUE THREAD

**Issue by wbwseeker** [spacy-io/spaCy#362]
The parameter of `StateC.set_break(int i)` is never used in the function's body: https://github.com/spacy-io/spaCy/blob/master/spacy/syntax/_state.pxd#L283
The function will therefore always set the break on the first item in the buffer.

However, the Break transition here wants to set it on the left_edge of the first item in the buffer: https://github.com/spacy-io/spaCy/blob/master/spacy/syntax/arc_eager.pyx#L240
This will only make a difference for tokens that have been shifted back onto the buffer (unshift), but it will not work as expected since `set_break()` doesn't actually use the provided value of its parameter.

**Comment by honnibal** [comment]
Wow. I'm sure I'd seen this bug before ages ago, but I guess I fixed it on a branch and never pushed it.

The fix is obvious. It'd be nice to have tests and to run the required experiment.

Do you want to do that, or shall I?

**Comment by wbwseeker** [comment]
with obvious, you mean replacing `this.B(0)` with `i` in the functions body, I assume.
I am writing tests for this right now anyway, so I'll do it. What kind of experiment do you have in mind for this?

**Comment by honnibal** [comment]
Retraining both the English and German parsing models, and evaluating the difference on the dev data.

**Comment by honnibal** [comment]
Hmm. I think the former behaviour of the `Break` transition masked this bug. Remember how the `Break` transition used to have that constraint, where you could only beak at a token boundary? That meant that you couldn't build a left tree before inserting the break. This bug may have been why that version of the transition system was doing better.

Interested to see the impact on accuracy!

**Comment by honnibal** [comment]
(Pasting results from @wbwseeker into here for future reference)

Before
UAS 91.1190112106
LAS 89.1020833536

After:
UAS 91.1569449423
LAS 89.1333821627

So, not much difference. Fixed now, anyway.
