### ISSUE TITLE
text u'a......b' generates an exception when parsed

### ISSUE THREAD

**Issue by udibr** [spacy-io/spaCy#378]
Following code generate an exception

    nlp = spacy.load('en')
    doc = nlp(u'a......b')

<pre>
/Users/udi/anaconda2/lib/python2.7/site-packages/spacy/tokens/doc.pyx in spacy.tokens.doc.Doc.push_back (spacy/tokens/doc.cpp:8356)()
    280         t.l_edge = self.length
    281         t.r_edge = self.length
--> 282         assert t.lex.orth != 0
    283         t.spacy = has_space
    284         self.length += 1

AssertionError: 
</pre>

**Comment by honnibal** [comment]
This should be fixed in v0.101.0. Are you using that version?

**Comment by udibr** [comment]
I used conda to install it:
spacy                     0.100.7                  py27_0    spacy

**Comment by honnibal** [comment]
Unfortunately the conda version is temporarily behind. If you do `pip install -U spacy`

**Comment by udibr** [comment]
working
