### ISSUE TITLE
Lemmatization of "Coping"

### ISSUE THREAD

**Issue by nartz** [spacy-io/spaCy#389]
The lemmatization of the word coping is transformed into cop instead of 'cope':
```
nlp(u'I am having trouble coping with this problem')[4].lemma_
-> u'cop'
```

**Comment by honnibal** [comment]
Thanks! Fixed the data. You should be able to work around the issue by writing this rule in after loading the data:

    import spacy

    nlp = spacy.load('en')
    
    nlp.vocab.morphology.lemmatizer.exc[u'verb'][u'coping'] = ('cope',)

The lemmatizer is called when the POS tag is assigned to the word. It loads the exception data on start-up, and stores it in Python dicts. The `.exc` member of the lemmatizer is a dict-of-dicts, where the outer keys are `"adj"`, `"noun"` and `"verb"`, and the inner keys are the word forms. The inner values are tuples of strings.

**Comment by adam-ra** [comment]
I'm sorry to say this but your workaround does not work. BTW the lemma is also wrong for the noun “ass”.

```
import spacy

nlp = spacy.load('en')
nlp.vocab.morphology.lemmatizer.exc['verb']['coping'] = ('cope',)
nlp.vocab.morphology.lemmatizer.exc['noun']['ass'] = ('ass',)

parsed = nlp('I am having trouble coping with my ass')
print(parsed[4].pos_, parsed[7].pos_)
print(parsed[4].lemma_, parsed[7].lemma_)
```

Output:
```
VERB NOUN
cop as
```

I'm using Python 3, so I've used normal string syntax for unicode strings.
