### ISSUE TITLE
Question about Hyphen Tokenization

### ISSUE THREAD

**Issue by Terrilocks** [spacy-io/spaCy#396]
In previous versions of spaCy, there were some inconsistencies with hyphen tokenization: 
e.g. next   -   of-kin. 
These have now been fixed and all hyphenated words get tokenized as follows: 
e.g. next  -  of  -  kin.

This is a lot better than before, but I'd still be interested to know why spaCy tokenises hyphens in this way when most other well-known NLP libraries choose to keep everything together: 
e.g. next-of-kin. 

Even though you can fairly easily trick other libraries with strings such as "This-is-a-sentence", it still seems preferable to treat "next-of-kin" as a simple NN, rather than a JJ-HYPH-IN-HYPH-NN sequence. 

I would also have thought most training data for POS taggers etc. usually keeps such sequences together, so it also seems unusual that everything is split by default.

**Comment by honnibal** [comment]
It really comes down to the fact that we train and evaluate on OntoNotes 5, where most NLP tools evaluate on the older Penn Treebank 3 data, specifically the WSJ section.

If you want next-of-kin to be kept together, you could add a rule to the tokenizer. This is now exposed in the API:

```python

tokenizer.add_special_rule(u'next-of-kin', [{'F': 'next-of-kin', 'L': 'next-of-kin', 'P': 'NN'}])
```
