### ISSUE TITLE
Loading the language model without wordvectors

### ISSUE THREAD

**Issue by jmizgajski** [spacy-io/spaCy#400]
Hi Matthew, 

I was wondering if there is a way to load a language model without the word vectors (which are pretty heavy on memory use). 

The use case for this is when you have a lot of micro services and some of them need to use the language model but do not require word vectors, so there is no need to have them in memory.

**Comment by jmizgajski** [comment]
To add to that it would be great if one could select the components of spacy that will be needed during execution in the load function, so you can also deselect other features (if possible) and save on not loading their models. 

For now the only way to do this is to manually override the word2vec model (this saves some loading time and considerable memory).  This could be further extended to sputnik so it only downloads the features that are needed, which could speed up the time needed to create a new instance of once's service (for example when using ansible).

P.S. > Here is a script if someone needs a workaround 

```python
# -*- coding: utf-8 -*-
from os import path

import spacy.en
from spacy.vocab import write_binary_vectors
import bz2

bin_loc = path.join(path.dirname(spacy.__file__), 'data', 'en-1.1.0', 'vocab', 'vec.bin')
lines = 'dog 0.1'.encode()
mini_vec = 'minivec.txt.bz2'
with bz2.BZ2File(mini_vec, 'w') as f:
    f.write(lines)

write_binary_vectors(mini_vec, bin_loc)

```

**Comment by jmizgajski** [comment]
Hi, did you guys had a chance to have a look at this? Should not be too hard for someone who understands the loading system. @honnibal ?

**Comment by honnibal** [comment]
As discussed in #506, `vectors=False` will work as expected in 1.0.
