### ISSUE TITLE
Is there a way to extract the "confidence" of the parse?

### ISSUE THREAD

**Issue by tokestermw** [spacy-io/spaCy#406]
In dependency parsing, some sentences are parsed accurately since the sentence pattern occurs more frequently. You've previously mentioned [imperatives don't work well](https://github.com/spacy-io/spaCy/issues/144#issuecomment-149588906) since it's not in the training set.

I think it would be informative if there was a way to extract the "confidence," or probability of the parse. Unsure parses can be deweighted for downstream tasks.

Probably not within the scope of the API but maybe it can be exposed if we're training our own SpaCy model?

**Comment by honnibal** [comment]
The current model doesn't give you particularly good information in this respect. It's locally normalised, and the perceptron loss isn't a good fit for this type of task.

I would recommend that if this type of information is important for your application, that you should consider training a model that extracts features from a parse and tries to predict either a binary good/bad label, or perhaps you could do a regression model, on the number of errors.

**Comment by tokestermw** [comment]
Right.

Thanks for the quick feedback as always.

**Comment by honnibal** [comment]
#881
