### ISSUE TITLE
Loading New Word Vector Tutorial

### ISSUE THREAD

**Issue by thecolorblue** [spacy-io/spaCy#407]
I am looking into loading new word vectors into spacy but I don't know what the floats referred to in the tutorial should be.

"Each entry consists of a key string, followed by a sequence of floats. Each entry should have the same number of floats."

What do the floats for each key string correspond to? How are they generated? 

Thanks.

**Comment by honnibal** [comment]
Sorry for not getting to this earlier.

The word vector loading is now a lot smoother, and a new tutorial will be written.

For the record: the "floats" the tutorial referred to are your word vectors =/.
