### ISSUE TITLE
calling sents() on empty string

### ISSUE THREAD

**Issue by nartz** [spacy-io/spaCy#411]
I guess it was unexpected to get this error:
[s for s in nlp(u'').sents] -> IndexError: list index out of range

I.e. calling sents on an empty string errors out - I wonder if this is the right behavior, or if sents should return an empty array?

**Comment by syllog1sm** [comment]
Thanks.

This should either return an empty list or yield out of an empty generator (off the top of my head, I don't remember whether `.sents` is a generator...Which is probably a bad sign. =/)
