### ISSUE TITLE
Updated version of plac breaks spacy.en.download.

### ISSUE THREAD

**Issue by ryangrimm** [spacy-io/spaCy#414]
Looks like python plac has been updated and is breaking the model download. Inside the spaCy requirements.txt file a version for plac hasn't been specified and it appears like the latest version of plac isn't backwards compatible (I haven't dug into this at all).

However, with a fresh install of spaCy (which succeeded) and then downloading the model via `python -m spacy.en.download`, the following error results:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/spacy/en/download.py", line 7, in <module>
    import plac
  File "/usr/local/lib/python2.7/site-packages/plac.py", line 38, in <module>
    from plac_tk import TkMonitor
  File "/usr/local/lib/python2.7/site-packages/plac_tk.py", line 46
    print('Process %d killed by CTRL-C' % os.getpid(), file=sys.stderr)
                                                           ^
SyntaxError: invalid syntax
```

However, this problem can be worked around if I specify plac==-0.9.1 in my own requirements.txt file.

```
plac==0.9.1
spacy==0.101.0
```

**Comment by pquentin** [comment]
I investigated a bit. Until https://github.com/micheles/plac/issues/17 is fixed I think spaCy should require `plac==0.9.2` (the last version without the universal wheel that only works on Python 3).

**Comment by honnibal** [comment]
Thanks, will pin!

**Comment by pquentin** [comment]
micheles/plac#17 is now fixed.
