### ISSUE TITLE
New features Document difference with Spacy

### ISSUE THREAD

**Issue by arita37** [spacy-io/spaCy#415]
I have a series of documents A and B, and would like to compute the difference:
   Produce a document C containing words/semantics such C= A-B (in A but not in B).

It might be similar to Word2Vec but, applied the whole document.

Do you think this is possible ?

**Comment by honnibal** [comment]
If you want a whole document back out, this will be difficult, and you'll need to carefully think/plan out how to train a model to minimise that objective. There's a literature on "neural style transfer" that's relevant.

**Comment by arita37** [comment]
Ok, thx.
Suppose I have only 2 documents A and B of 500 words each.
How can I compute the difference A-B  (just similarity in words) ?

Can I use Word to Vec or Sense to Vec ?

Thanks

**Comment by honnibal** [comment]
The following will get the difference in averaged vectors between the two documents, and then sort sentences of the two by their similarity to this difference:

    diff = doc1.vector - doc2.vector
    sents = list(doc1.sents) + list(doc2.sents)
    sents.sort(key=lambda sent: cosine(sent.vector, diff)
    for sent in sents:
        print(sent.text)

This isn't very clever, though, and might not get good results.
