### ISSUE TITLE
Best practice question: Different entity matchers using one instance?

### ISSUE THREAD

**Issue by viksit** [spacy-io/spaCy#428]
In a use case where one spacy instance (english) is shared amongst various callers (services), I'd like each caller to have it's own `Matcher` or `PhraseMatcher` instance - are there any suggestions on the best way to implement this?

@henningpeters @honnibal there was some discussion about this in an issue but I can't seem to find it again?

**Comment by syllog1sm** [comment]
The `Matcher` instance should be quite lightweight, since it takes a reference to the `Vocab` object. So I would suggest that yes --- go ahead and create a new `Matcher` object.

You'll then just apply the `Matcher` to the `Doc` object explicitly:

```python

def client_process(nlp, patterns, texts):
    matcher = Matcher(nlp.vocab, patterns=patterns)
    for text in texts:
        doc = nlp(text)
        matcher(doc)
        # Do stuff...
```
