### ISSUE TITLE
Lemma for 'dive' as noun

### ISSUE THREAD

**Issue by raghavgupta93** [spacy-io/spaCy#435]
Shows up as 'diva' in my experiments - can you please check? Thanks!

**Comment by honnibal** [comment]
I had assumed there was a simple data error here, but actually this points to something deeper.

The WordNet data gives the mapping of the *plural* forms of nouns to their base form. The lemmatizer was applying this mapping to all noun forms --- both plural and non-plural. This means that "dive" as a singular noun was matching a weird plural form of "diva", "dive". I doubt any instance of the token "dive" will *ever* mean "divas" --- it's much more likely to be a POS tagging error. But the problem in the lemmatization logic may have had other effects.

Thanks for the report!
