### ISSUE TITLE
Noun chunks are not extracted

### ISSUE THREAD

**Issue by EgorLakomkin** [spacy-io/spaCy#439]
```
import spacy
nlp = spacy.en.English(entity = False)
doc = nlp(u"good facilities and great staff")
noun_chunks = list(doc.noun_chunks)
```

noun_chunks will be empty list in this case. Shouldn't it extract ["good facilities", "great staff" ]?

**Comment by honnibal** [comment]
It should, but unfortunately the statistical model isn't perfect, and it's hard to fix errors on individual mistakes.
