### ISSUE TITLE
Lemma for "saw" (past tense of "see")

### ISSUE THREAD

**Issue by clairempr** [spacy-io/spaCy#445]
Hi,

I've noticed that when dealing with sentences like "I saw a mouse yesterday.", spaCy sets the lemma of the word "saw" to "saw" rather than "see", even though it identifies the word as past tense with the tag VBD.

**Comment by honnibal** [comment]
As with Issue #445, I thought this was a simple data error — but actually my lemmatizer implementation had a mistake for these cases where there's a verb whose baseform is the same as another verb's inflected form (here "see/saw" vs "saw/sawed").

This should be fixed now, in the upcoming 1.0 release. Thanks for the report.
