### ISSUE TITLE
Loading the english model causing memory issues

### ISSUE THREAD

**Issue by SindhuBairavi** [spacy-io/spaCy#449]
Hi, I'm trying to use spacy for NER but when i try to load the model into the VM, there's always memory issues. How much memory is needed to load and is it possible to break it down?
Is there a way to load it into the cache and reuse instead of loading on every run of the code?
Thanks!

**Comment by amirouche** [comment]
Can you provide a traceback?

**Comment by syllog1sm** [comment]
It's not really a satisfying solution, but if you just want the NER, and don't need the parser, you can do:

```python

nlp = spacy.load('en', parser=False)

```

This will greatly reduce the memory requirements.

**Comment by SindhuBairavi** [comment]
@amirouche : It just says 'Killed' on the VM but runs on my local. So figured that it's a memory issue. And the script explicitly says 1.6GB which the VM does not have.
@syllog1sm : Thanks man!  This did help reduce the memory. It uses 0.9GB now. Definitely an improvement. 
Do you know if we can cache load the model?
