### ISSUE TITLE
empty doc when instantiated from pre-existing tokens

### ISSUE THREAD

**Issue by ifp-markreinke** [spacy-io/spaCy#451]
When instantiating a Doc from pre-existing tokens as explained here https://spacy.io/docs/tutorials/byo-annotations the resulting doc is empty:
`doc = Doc(nlp.vocab, [('A', True), ('token', False), ('!', False)])`

**Comment by mzhai2** [comment]
I can confirm.
doc = Doc(nlp.vocab, orth_and_spaces=zip(tokens, has_space))
gives
TypeError: __init__() got an unexpected keyword argument 'orth_and_spaces'

Also, when should the spaces list be all true or all false when it is not known?

**Comment by ifp-markreinke** [comment]
The exception you get is because of a typo in the docs. It should be 'orth**s** and spaces' instead of 'orth_and_spaces'.

**Comment by honnibal** [comment]
Actually the `orths_and_spaces` argument was broken as well — fixed now, thanks!

I've also made the change to the docs, which is pending deployment to the site.
