### ISSUE TITLE
How do I interpret the parser output?

### ISSUE THREAD

**Issue by tastyminerals** [spacy-io/spaCy#467]
Here is a sentence: *"There is a green tree in the garden."*
Following your docs, when it is parsed the output is the following:
```
[[381],
 [],
 [379, 369],
 [367, 369],
 [369],
 [405, 369],
 [379, 401, 405, 369],
 [401, 405, 369],
 [407]]
```
How do I interpret these funny numbers :) ?

I expected:
```
(ROOT
  (S
    (NP (EX There))
    (VP (VBZ is)
      (NP
        (NP (DT a) (JJ green) (NN tree))
        (PP (IN in)
          (NP (DT the) (NN garden)))))
    (. .)))
```

**Comment by Ogaday** [comment]
What's the code you used to produce that output? I imagine you need to append an underscore (`_`) to the tags you're printing for it to make more sense to you. https://spacy.io/docs#token-postags

**Comment by tastyminerals** [comment]
I used "Syntactic dependencies" example on a web page.

```
import spacy
en_nlp = spacy.load('en')
en_doc = en_nlp(u'There is a green tree in the garden.')

def dependency_labels_to_root(token):
    '''Walk up the syntactic tree, collecting the arc labels.'''
    dep_labels = []
    while token.head is not token:
        dep_labels.append(token.dep)
        token = token.head
    return dep_labels

[dependency_labels_to_root(tok) for tok in en_doc]
```

**Comment by Ogaday** [comment]
Try

    def dependency_labels_to_root(token):
        dep_labels = []
        while token.head is not token:
            dep_labels.append(token.dep_)    #see underscore here
            token = token.head
        return dep_labels

I'm still wrapping my head round Spacy's data model and NLP in general myself, but spacy uses numbers to refer to words and labels - for the sake of clarity I believe. `dep`, `pos` and `tag` can all be followed by underscore to see the string representation, as I linked above, or you can use the `StringStore` table which can be accessed by `en_nlp.vocab.strings` ie. `en_nlp.vocab.string[381]`. See [here](https://spacy.io/docs#stringstore).

Another note, I'm not sure that `dependency_labels_to_root` gives you what you're looking for exactly, but I hope this is helpful.

**Comment by mastasky** [comment]
Someone should mark issues like this as closed.

**Comment by xzegga** [comment]
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-edf97381b54c> in <module>()
      3 range1 = lambda start, end: range(start, end+1)
      4 
----> 5 for start, end in en_doc.sents:
      6     print(''.join(tokens[i].string for i in range(start, end)))

ValueError: too many values to unpack (expected 2)
`

**Comment by Ogaday** [comment]
@xzegga is this what you're trying to do?

```python
import spacy


nlp = spacy.load('en')
doc = nlp(...)
for sent in doc.sents:
    print(''.join(tok.string for tok in sent))
```
