### ISSUE TITLE
Named Entity Recognition : how to get accepted words for Entity type?

### ISSUE THREAD

**Issue by vinoth459** [spacy-io/spaCy#475]
I have started working spacy since last week. I have requirement to get words which belongs to 'MONEY' entity type. Here is my queries, 
How could I get words which belong to MONEY Entity type? or which have been configured in Spacy?

I am following below link for creating new entity.
https://github.com/spacy-io/spaCy/issues/187
How could  I open entity model file?

Thanks in advance.

**Comment by vinoth459** [comment]
Hi ,

I have found which words are maching for Money entity:
€, ¥, £, $, R$, ₹, ₩

Please find my input:
€ 10,000
¥ 10,000
£ 10,000
$ 10,000
R$ 10,000
₹ 10,000
₩ 10,000

If I want to add few more entities like **POUND, Dollar, Yen ,Rupee ,EURO** to existing Money entity ,  then what needs to be changed or implemented? Please suggest me.

**Comment by ahelaatabi** [comment]
Hey, 
You may look for how to add new entities here...
https://github.com/spacy-io/spaCy/blob/master/examples/matcher_example.py

**Comment by vinoth459** [comment]
Thanks buddy..let me check it

**Comment by Quamber** [comment]
@vinoth459 I have some message's like "You have 10,000/- in your account" how can i add #/- as money in spacy?
