### ISSUE TITLE
Issue with doc.from_array

### ISSUE THREAD

**Issue by Ogaday** [spacy-io/spaCy#477]
I've been following the tutorial here, specifically my own dependency parsing and I've come across some unexpected behaviour, see [gist](https://gist.github.com/Ogaday/f06bf048f29a03598e90a263269cedc9). On running I occasionally get a `Segmentation fault (core dumped)` printed to the terminal after printing. The final statement in the gist raises an `IndexError`.

I've had a brief look at the source, but I can't see the issue and thought I would share it while I look further.

More info:
```
spacy 0.100.7 py35_0  (conda)
python 3.5.2 (conda)
Ubuntu-Mate 16.04 Xenial
Intel Core i3-5005U CPU @ 2GHz
```

Thanks for any advice.

**Comment by honnibal** [comment]
Hi,

Sorry for the delay getting to this. Could you update to 0.101.0, and try again? You'll need to do:

`pip install -U spacy==0.101.0 && python -m spacy.en.download --force`

If it's still a problem, report back?
