### ISSUE TITLE
Brown clusters aren't very useful

### ISSUE THREAD

**Issue by Kharms** [spacy-io/spaCy#481]
Looking at the Brown clusters of the lower case words:

81.5% fall into cluster 0, (429279/526544)
02.4% fall into cluster 22,
<1% fall into every other cluster. 

Perhaps the problem is that the clustering capped at 1000 clusters?

```
import operator
import spacy
parser = spacy.en.English()

clusters = {}
count_of_lower = 0
for w in parser.vocab:
    if w.is_lower:
        count_of_lower +=1
        clusters[w.cluster] = clusters.get(w.cluster, 0) + 1
sorted_clusters = sorted(clusters.items(), key=operator.itemgetter(1),reverse=True)
print('lower case tokens: ' + str(count_of_lower))
for i,c in enumerate(sorted_clusters):
    if i>10:
        break
    print('% of tokens in cluster_' + str(c[0]) +': ' +str(round(c[1]/count_of_lower,3)))

```

A potential solution would be to compute the hierarchical Brown cluster for each token in the form '100010100100...' where each bit is a fork in tree and and then have the token.cluster be a function that takes 'depth' as an argument, going from outside in. So a depth of 0 would be the token itself, depth of 2 would be a cluster of 4, depth of 5 would be a cluster of 32, and so on. This would allow comparison of nearby clusters of an arbitrary size.

**Comment by honnibal** [comment]
I think you're getting tricked by Zipf's law here. Count the cluster frequencies by token, not by type --- or weight the count by exp(w.prob). You'll come to a very different perspective.

Admittedly the Brown clusters are a bit mysterious. If you inspect the clustering, they don't look at all impressive. But empirically they improve the accuracy of the POS tagger and parser quite a lot.

**Comment by Kharms** [comment]
Neat, running the above weighted by probability each word does paint a somewhat more balanced set of classes, but I'd still argue that the current clustering implementation isn't reaching its full potential. 

This paper has some interesting stuff on this topic: http://www.derczynski.com/sheffield/papers/brown_impact.pdf

> The best possible c behaves oppositely with class-only and path-only information. For class-only, with small corpora, c should be high (or set to |V |); as the corpora grow, so the best c levels off. Conversely, for path-only, small corpora benefit from lower c, whereas larger corpora do better with high values of c. This is be- cause as c → |V |, more path information is added, whereas clustering information decreases, as suggested in Section 3.

>With the class-only experiment, performance peaks and then declines as c → |V |, as expected (Section 3).

>In the path-only experiment, performance increases with both |T | and c.

Curiously, the metric you mention (PoS tagging) appears to peak in their tests at a c=640, I imagine this is because semantic similarity matters far less, so if you build your clusters with PoS in mind it results in clusters that are semantically dissimilar but very well at the task. 

> For PoS tagging, we see that there is a peak performance with c = 640, after which accuracy drops unstably (Table 4). This matches our expec- tations. In fact, the performance for c = 1000 (the value used to generate the original clusters for the CMU tagger) is a local minimum in our test. The PoS task involves a lot of other factors, and so is not as close an estimate of clustering quality as the NER task is, but it does make use of both the clus- ters and the hierarchy. No clear result came from varying |T | with a fixed c (Table 5), unlike in NER, where increasing |T | had a strong impact.

**Comment by honnibal** [comment]
Well, the feature functions for the POS tagger, NER and parser actually use 4 and 6 bit prefixes of the cluster codes, following Koo and Collins (2010).

The details of the clustering stuff are overall pretty unsatisfying, but it does all work, and re-engineering the details of the linear models aren't a priority at this point. It's much better to complete the switch to the neural network. I'll therefore close this.
