### ISSUE TITLE
Using syntaxnet for dependency tree parsing?

### ISSUE THREAD

**Issue by davidkell** [spacy-io/spaCy#484]
Is there a way to use syntaxnet "under the hood" to generate the spacy doc object, including dependency tree and pos tagging?

**Comment by honnibal** [comment]
See here for how to load annotations acquired from some arbitrary source, such as SyntaxNet, into spaCy: http://spacy.io/docs/tutorials/byo-annotations

**Comment by davidkell** [comment]
Awesome, thanks!

**Comment by honnibal** [comment]
No problem!

There will be more than a little glue required to piece the system together. If you get it all working in a deployable state, a Docker container would be much appreciated.
