### ISSUE TITLE
german model fails to download

### ISSUE THREAD

**Issue by fkuhn** [spacy-io/spaCy#489]
After installing spacy, I downloaded the English model
via ``spacy.en.download``.
However, using ``spacy.de.download`` to download the German model throws an exception:
``sputnik.package_list.PackageNotFoundException: de>=1.0.0,<1.1.0``
Any recommendations?
Best,
Florian

**Comment by honnibal** [comment]
Ah. Sorry.

Try now.

**Comment by fkuhn** [comment]
Hi,
it's working now. Thanks a lot!
Best,
F
