### ISSUE TITLE
Add 'head token index' attribute to words in nlp(doc)

### ISSUE THREAD

**Issue by cainesap** [spacy-io/spaCy#492]
When navigating a spaCy-processed document, e.g --
````
from spacy.en import English
nlp = English()
doc = nlp('The old man shook hands with the young man.')
for word in doc:
    print(word, word.tag_, word.head)
````
-- which outputs:

> The DT man
> old JJ man
> man NN shook
> shook VBD shook
> hands NNS shook
> with IN shook
> the DT man
> young JJ man
> man NN with
> . . shook

It would be great to have a token number stored with the head (i.e. word.headi or something like that). This would allow you to unambiguously identify the head (e.g. man_3 versus man_9 in this sentence).

**Comment by honnibal** [comment]
Each token has a `.i` attribute. So `token.head.i` should give you exactly what you want.

**Comment by cainesap** [comment]
So it does! Wasn't thinking recursively enough .. thank you

**Comment by cainesap** [comment]
Can I ask a related question: in the sentence, "I want a flight to Berlin er I mean Munich", there are disfluencies that would be removed from the parse tree with Redshift (so that 'Berlin er I mean' is edited away) .. has that been incorporated in spaCy in some way? I can't see that it has, in which case, is there a plan to do so?

**Comment by honnibal** [comment]
There's no immediate plan to use the `Edit` transition. There aren't enough speech users, and people don't know they want disfluency detection :p.

Try using a bidirectional LSTM to pre-process. It'll probably work really well.
