### ISSUE TITLE
Subject Object Extraction

### ISSUE THREAD

**Issue by cloutier** [spacy-io/spaCy#493]
HI

Hope all is well

So lately I have been playing around with the spacy model and python code written by https://nicschrading.com/project/Intro-to-NLP-with-spaCy/

In the section for subject verb object extraction I keep getting an error no module named subj_obj_extraction found

Is there an alternative way to implementing Subject-Verb-Object extraction within Spacy?

**Comment by Ogaday** [comment]
The module `subj_obj_extraction` isn't a part of the spaCy package, it's written by Schrading himself, and can be found here: https://github.com/NSchrading/intro-spacy-nlp/blob/master/subject_object_extraction.py
