### ISSUE TITLE
Errors in docs on spacy.io label:docs 

### ISSUE THREAD

**Issue by radixvinni** [spacy-io/spaCy#495]
Section [Navigating the Parse Tree](http://spacy.io/docs/#token-navigating) does not include `dep\dep_` - universal dependency label.

It would also be nice to have an overview for `Token` class like there is one for `Span` and all other classes.

Example in section [Doc.ents](http://spacy.io/docs/#doc-spans-ents). The last line has no meaning. It is always `True`.

**Comment by syllog1sm** [comment]
Thanks! Fixed in the website source.
