### ISSUE TITLE
Sputnik can't download English Model

### ISSUE THREAD

**Issue by amitvpatel06** [spacy-io/spaCy#496]
When I run: sputnik --name spacy --repository-url http://index.spacy.io install en==1.1.0
I get the following error:
Traceback (most recent call last):
  File "/mnt/castor/seas_home/a/amitpate/HypeNET-master/venv/bin/sputnik", line 11, in <module>
    sys.exit(main())
  File "/mnt/castor/seas_home/a/amitpate/HypeNET-master/venv/lib/python2.7/site-packages/sputnik/__main__.py", line 12, in main
    args.run(args)
  File "/mnt/castor/seas_home/a/amitpate/HypeNET-master/venv/lib/python2.7/site-packages/sputnik/cli.py", line 45, in run
    repository_url=args.repository_url)
  File "/mnt/castor/seas_home/a/amitpate/HypeNET-master/venv/lib/python2.7/site-packages/sputnik/__init__.py", line 23, in install
    data_path = default_data_path(app_name)
  File "/mnt/castor/seas_home/a/amitpate/HypeNET-master/venv/lib/python2.7/site-packages/sputnik/util.py", line 26, in default_data_path
    raise UnknownAppNameException(app_name)
sputnik.util.UnknownAppNameException: spacy

**Comment by syllog1sm** [comment]
I'd really like to change how `sputnik` works. I found this very confusing too.

I think this error probably means you don't have spacy installed, or at least, not installed within the same environment that `sputnik` is installed within. Try doing `ls /mnt/castor/seas_home/a/amitpate/HypeNET-master/venv/lib/python2.7/site-packages/spacy` to check.

**Comment by amitvpatel06** [comment]
Should spacy have sputnik installed within it? My site-packages has both but sputnik is not inside spacy

**Comment by kunal047** [comment]
I am getting a `bad interpreter: No such file or directory` error while trying to download.

**Comment by ines** [comment]
Should hopefully be fixed now – just posted this in #507:

> We've been moving the site over to new servers and fixing the SSL certificate to finally address the model downloading issues. The problem was that @honnibal was using CloudFlare's "flexible" SSL option. We now got rid of that and installed a certificate from [Let's Encrypt](https://letsencrypt.org) (which is great, btw!)
> 
> Make sure to flush your DNS cache before you reload and try again:
> In Chrome: `chrome://net-internals/#dns`
> On Mac / OSX 10.11+: `sudo dscacheutil -flushcache`
> 
> Alternatively, you can also use [Google Public DNS](https://developers.google.com/speed/public-dns/), which has already updated. That's also what we used for debugging internally for the past few hours. Unfortunately, the DNS is still propagating and seems to be taking forever (see [here](http://viewdns.info/propagation/?domain=spacy.io) for the current status).
