### ISSUE TITLE
Model Download behavior

### ISSUE THREAD

**Issue by lababidi** [spacy-io/spaCy#500]
I have a gripe with the `spacy.download.download()` mechanism. 

I would like to programmatically download a model if it does not exist.
If it exists, I do not want to overwrite it, I want the code to effectively `pass`.

My gripe is the current structure of `download` does not allow for this process to happen as I described. Currently, if a model exists, `download` fails. @honnibal any suggestions?

**Comment by lababidi** [comment]
I found a workaround for now. Surrounding with a Try/Except with `SystemExit`
will prevent the application from exiting.

Nevertheless, I suggested an edit in #501

**Comment by honnibal** [comment]
Thanks, and agreed --- merged.

**Comment by somenick** [comment]
Doesn't it duplicate #454 in a way?

Also, is there a release planned in the near future?
