### ISSUE TITLE
Suggestion-  Cloud9 setup steps

### ISSUE THREAD

**Issue by patilvish1** [spacy-io/spaCy#509]
Hi Matt
   This is great stuff and thanks for sharing your product with rest of the world. 
   Is there any way you can give instructions to setup this on cloud9 ?
   This will help people to get on board quickly and start exploring. 

Thanks
Vishal

**Comment by honnibal** [comment]
I'm afraid I don't know what that is =/. Am I getting old?

**Comment by patilvish1** [comment]
I am assuming the question is what is cloud9 ..

https://c9.io/ provides online development environment for various languages including Python .
It is on Ubuntu .

The best part is it is free if you create public Workspaces  (or cost very less dollars if you need more than one private workspace  ).


I tried to set it up your code, however it failed because the setup files need write access to use/bin folder . Wondering if there is any way you can help in setting it up ( whenever you have time ).

**Comment by aborsu** [comment]
If you install using pip --user it will install it locally and not require access to any root folders.

**Comment by patilvish1** [comment]
Awesome.. That helped ..

At the end,I ran 
     python -c "import spacy; spacy.load('en'); print('OK')" 

Got "OK" .. so i am all good  ...
 

one small  correction :)
   cd spaCy

I noticed that it is still using python2.7. Need to play with cloud 9 settings (tried project setting .. it didnot work)..

**Comment by honnibal** [comment]
You should probably try using virtualenv if you want to install locally in Python3. Anyway. Closing this :)

**Comment by patilvish1** [comment]
Thanks both of you.

Here is updated script (with correction in case )


sudo apt-get update
sudo apt-get install python-dev
git clone https://github.com/spacy-io/spaCy.git
cd spaCy
pip install --user -r requirements.txt
pip install --user -e .

python -c "import spacy; spacy.load('en'); print('OK')"

**Comment by patilvish1** [comment]
Matt
	I recommend you add following section to your installation page. Definitely it will help people get going in less than 5 mins. 
  


Steps to Create cloud9 environment with python3 virtual environment 
===================================================================

Please note cloud9 uses ubuntu and current default version for python is 2.x

1. Create a python workspace in cloud9 (do not include git path)
2. Delete all files inside the root folder (e.g. readme file and example folder)
3. Goto bash window and run following commands

 sudo pip install virtualenv
 sudo apt-get update
 sudo apt-get install python-dev
 git clone https://github.com/spacy-io/spaCy.git
 virtualenv spaCy  -p /usr/bin/python3
 source spaCy/bin/activate
 cd spaCy
 pip install  -r requirements.txt
 pip install -e .


4. Verify python version as and installation is perfect, by typing following commands in bash window 

 python --version  
 python -c "import spacy; spacy.load('en'); print('OK')"
