### ISSUE TITLE
Is it possible to only load part of Spacy model?

### ISSUE THREAD

**Issue by jltchiu** [spacy-io/spaCy#511]
Hi All,

right now for loading English model, I use 

NLP = spacy.load('en')

I wonder is there a way to only load part of the model? For example ignoring the word embedding model since I am only using the parser for NER, POS, dependency parsing. 

Thanks.

**Comment by honnibal** [comment]
Stay tuned for the 1.0 release candidate :)

https://github.com/spacy-io/spaCy/issues/506
